### ISSUE TITLE
jupyterhub upgrade broke globus auth

### ISSUE THREAD

**Issue by rabernat** [jupyterhub/zero-to-jupyterhub-k8s#1215]
We recently upgraded a jupyterhub to

- jhub helm chart=0.8.2
- JupyterHub v.=0.9.6

This hub uses globus auth with the following config:
```yaml
pangeo:
  jupyterhub:
    proxy:
      secretToken: XXX
    auth:
      type: globus
      globus:
        clientId: "XXX"
        clientSecret: "XXX"
        callbackUrl: "https://staging.ocean.pangeo.io/hub/oauth_callback"
        identityProvider: "orcid.org"
      admin:
        access: true
        users:
          - "0000-0001-7479-8439" # Joe Hamman
          - "0000-0001-5999-4917" # Ryan Abernathey
          - "0000-0003-4004-4553" # Raphael Dussin
```

On redeploy, we got this error
```
[E 2019-04-02 17:42:34.846 JupyterHub app:1958]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1955, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1639, in initialize
        self.load_config_file(self.config_file)
      File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-5>", line 2, in load_config_file
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 598, in load_config_file
        raise_config_file_errors=self.raise_config_file_errors,
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.6/dist-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/srv/jupyterhub_config.py", line 291, in <module>
        set_config_if_not_none(c.GlobusOAuthenticator, trait, 'auth.globus.' + cfg_key)
    TypeError: must be str, not NoneType
```

The hub is deployed via hubploy, with full details here:
https://github.com/pangeo-data/pangeo-cloud-federation/tree/staging/deployments/ocean

Any ideas what might have gone wrong?

cc @jhamman

**Comment by consideRatio** [comment]
Hmmmmm... the hub image is the one provided with the chart, right?

**Comment by consideRatio** [comment]
I think the helm chart 0.8.2 does not contain this fix, and you will be fine using the latest dev release.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/4e9b4a22f516a7f7545c1cfebe440f0b2dde5a6d

**Comment by consideRatio** [comment]
Seems resolved, closing.
