### ISSUE TITLE
Hub crash after timeout trying to access the proxy-api service

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1369]
I have three nodes where my JupyterHub non-user pod resides. During a k8s version upgrade of these nodes, causing one to be cordoned at the time, the hub pod crashes before it has been moved. I'm currently very confused to why the request to the proxy pod timed out like below.

No matter if we can avoid this error, it is worth considering if we can add some error handling to this.

__Logs from the hub pod__
Note that this can occur anytime as I believe a call to check_routes is scheduled to occur every 30 seconds. 

```
[E 2019-08-20 09:18:33.376 JupyterHub app:2482]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2480, in launch_instance_async
        await self.start()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2405, in start
        await self.proxy.check_routes(self.users, self._service_map)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 62, in locked_method
        return await method(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 315, in check_routes
        routes = await self.get_all_routes()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 804, in get_all_routes
        resp = await self.api_request('', client=client)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 773, in api_request
        result = await client.fetch(req)
    tornado.curl_httpclient.CurlError: HTTP 599: Connection timed out after 20000 milliseconds
    
[D 2019-08-20 09:18:33.377 JupyterHub application:647] Exiting application: jupyterhub
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<JupyterHub.launch_instance_async() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/app.py:2477> exception=SystemExit(1,)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2480, in launch_instance_async
    await self.start()
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2405, in start
    await self.proxy.check_routes(self.users, self._service_map)
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 62, in locked_method
    return await method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 315, in check_routes
    routes = await self.get_all_routes()
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 804, in get_all_routes
    resp = await self.api_request('', client=client)
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/proxy.py", line 773, in api_request
    result = await client.fetch(req)
tornado.curl_httpclient.CurlError: HTTP 599: Connection timed out after 20000 milliseconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2492, in launch_instance
    loop.start()
  File "/usr/local/lib/python3.6/dist-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1451, in _run_once
    handle._run()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 2483, in launch_instance_async
    self.exit(1)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 648, in exit
    sys.exit(exit_status)
SystemExit: 1
```

**Comment by betatim** [comment]
Was the node that the proxy pod was running on cordoned at the time the hub pod tried to talk to it?

A pod on a cordoned node is considered "not ready" by a `Service` so it won't send traffic there. But pods are happy to run on a node that is cordoned.

I've run into this trap several times when removing nodes from the mybinder.org cluster or doing other maintenance. Though in my case it is usually the ingress pods that end up on a cordoned node which means all inbound traffic stops.

I'd be interested if we can add something to pods so that they don't "tolerate" being on a cordoned node. Then they'd get stopped and restarted on a different node.

An alternative is to change the `Service` object so that it doesn't consider pods on cordoned nodes as "not ready".

**Comment by consideRatio** [comment]
@betatim :heart: :tada: :heart:!!! That is a very important piece in the puzzle for me to grasp!

**Comment by consideRatio** [comment]
In k8s 1.13 and up, there is some automatic tainting and eviction related to taints going on, as can be read about [here](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#taint-based-evictions).

@betatim, an interesting part was this I think. I think it will take 5 minutes for various pods by default to get kicked out. For us, it may make sense to manually set this to something a lot lower on various pods I think. Because for example, imagine that the proxy pod is on a node that is cordoned, it will stop getting traffic to it through the service, but at the same time it won't get evicted and relocate either, which makes the proxy service go down for quite a while! I think the only reason not to evict quick is for a pod relates to if the pod is for example taking on calls that needs multiple seconds or minutes to finish, then this way would let the request to the pod on the cordoned node would have time to finish these request. It would not shut down automatically when that has happened though as it is blissfully unaware of what goes on until the 300 seconds has passed and it actually gets kicked out and has some graceful termination time to shut down as well.

> Note that Kubernetes automatically adds a toleration for `node.kubernetes.io/not-ready` with `tolerationSeconds=300` unless the pod configuration provided by the user already has a toleration for `node.kubernetes.io/not-ready`. Likewise it adds a toleration for `node.kubernetes.io/unreachable` with `tolerationSeconds=300` unless the pod configuration provided by the user already has a toleration for `node.kubernetes.io/unreachable`.

**Comment by betatim** [comment]
Reducing the time pods will hang around sounds like a good idea for all of our pods for which we only have one replica. I wouldn't set it to zero before investigating if it is possible for nodes to get cordoned for (very) short periods of time. It feels like we could start some kind of "domino effect" where the node is cordoned, the pod gets evicted instantly, restarts elsewhere, old node is uncordoned, the new node gets cordoned, pod gets evicted, endlessly repeating. Maybe wait for 10s or so before moving?

**Comment by consideRatio** [comment]
Closing in favor of PR discussion followup. Thanks @betatim for discussing this with me, it was the seed to figure out #1401 which had bugged me for a year or more.
