### ISSUE TITLE
Initialize without Helm

### ISSUE THREAD

**Issue by JWDobken** [jupyterhub/zero-to-jupyterhub-k8s#1384]
I am trying to install JupyterHub on a kubernetes cluster on which I am not supposed to init Tiller. So following this explanation to [use Helm without tiller](https://blog.giantswarm.io/what-you-yaml-is-what-you-get/); I am taking the following steps:

Fetch the repository:
```bash
helm fetch \
  --repo https://jupyterhub.github.io/helm-chart/ \
  --version 0.8.2 \
  --untar \
  --untardir charts \
  jupyterhub
```

Copy the values file (and added the secret token to the proxy settings):
```bash
mkdir values
cp -p charts/jupyterhub/values.yaml values/jupyterhub.yaml
```

Generate the maniscripts:
```bash
mkdir manifests
helm template \
  --name jupyterhub \
  --namespace jupyterhub \
  --values values/jupyterhub.yaml \
  --output-dir manifests \
    charts/jupyterhub
```

Now apply the manifest to the cluster:
```bash
kubectl create namespace jupyterhub
kubectl apply -n jupyterhub -R -f manifests/jupyterhub
```

**result**
All pods and services start as expected, no problems here. However, when I try to login; the container remains in a penging state:
<img width="1427" alt="Screenshot 2019-09-03 at 21 24 22" src="https://user-images.githubusercontent.com/15050499/64202374-497cb480-ce91-11e9-9b26-6dda78ab2c04.png">

> [Warning] 0/3 nodes are available: 3 Insufficient memory.

```bash
$ kubectl describe po -n jupyterhub jupyter-jwdobken
...
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     hub.jupyter.org/dedicated=user:NoSchedule
                 hub.jupyter.org_dedicated=user:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  18s (x5 over 114s)  default-scheduler  0/3 nodes are available: 3 Insufficient memory.
```

The hub simply gives a time-out:
```bash
$ kubectl logs -n jupyterhub hub-8567d9d56f-qjxnv -f
...
[I 2019-09-03 18:41:03.531 JupyterHub base:509] User logged in: jwdobken
[I 2019-09-03 18:41:03.532 JupyterHub log:158] 302 POST /hub/login?next= -> /user/jwdobken/ (jwdobken@10.133.246.74) 31.78ms
[I 2019-09-03 18:41:03.572 JupyterHub log:158] 302 GET /user/jwdobken/ -> /hub/user/jwdobken/ (@10.133.246.74) 0.98ms
[I 2019-09-03 18:41:03.687 JupyterHub reflector:199] watching for pods with label selector='component=singleuser-server' in namespace jupyterhub
[I 2019-09-03 18:41:03.756 JupyterHub reflector:199] watching for events with field selector='involvedObject.kind=Pod' in namespace jupyterhub
[W 2019-09-03 18:41:03.840 JupyterHub base:724] User jwdobken is slow to start (timeout=0)
[I 2019-09-03 18:41:03.841 JupyterHub base:1066] jwdobken is pending spawn
[I 2019-09-03 18:41:03.848 JupyterHub log:158] 200 GET /hub/user/jwdobken/ (jwdobken@10.133.246.74) 233.32ms
[I 2019-09-03 18:41:13.953 JupyterHub proxy:301] Checking routes
[I 2019-09-03 18:42:13.953 JupyterHub proxy:301] Checking routes
[I 2019-09-03 18:43:13.953 JupyterHub proxy:301] Checking routes
[I 2019-09-03 18:44:13.952 JupyterHub proxy:301] Checking routes
[I 2019-09-03 18:45:13.952 JupyterHub proxy:301] Checking routes
[E 2019-09-03 18:45:57.698 JupyterHub user:477] Unhandled error starting jwdobken's server: pod/jupyter-jwdobken did not start in 300 seconds!
[I 2019-09-03 18:45:57.699 JupyterHub spawner:1758] Deleting pod jupyter-jwdobken
[E 2019-09-03 18:45:57.874 JupyterHub gen:593] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py:629> exception=TimeoutError('pod/jupyter-jwdobken did not start in 300 seconds!',)> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 589, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 636, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1718, in _start
        timeout=self.start_timeout,
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/utils.py", line 155, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: pod/jupyter-jwdobken did not start in 300 seconds!
    
[W 2019-09-03 18:45:57.878 JupyterHub users:442] Stream closed while handling /hub/api/users/jwdobken/server/progress
```

**Comment by chicocvenancio** [comment]
` Warning  FailedScheduling  18s (x5 over 114s)  default-scheduler  0/3 nodes are available: 3 Insufficient memory.` is likely the issue, unrelated to helm.
I suggest you investigate the nodes, what is already scheduled into them and how much memory they have available.

**Comment by JWDobken** [comment]
@chicocvenancio nothing else but jupyterhub is currently running:

```bash
$ kubectl describe nodes
...
  Namespace                  Name                                              CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                                              ------------  ----------  ---------------  -------------  ---
  jupyterhub                 hook-image-puller-bspdd                           0 (0%)        0 (0%)      0 (0%)           0 (0%)         43m
  jupyterhub                 hub-c98cb97cd-xxknt                               200m (20%)    0 (0%)      512Mi (32%)      0 (0%)         44m
  jupyterhub                 user-scheduler-786c6f89d-clrhw                    50m (5%)      0 (0%)      256Mi (16%)      0 (0%)         43m
  kube-system                cilium-vg6sh                                      300m (30%)    0 (0%)      300Mi (19%)      0 (0%)         3h22m
  kube-system                csi-do-node-rrd82                                 0 (0%)        0 (0%)      70Mi (4%)        0 (0%)         3h22m
  kube-system                do-node-agent-xl4d4                               102m (10%)    102m (10%)  80Mi (5%)        100Mi (6%)     3h22m
  kube-system                kube-proxy-ncrv8                                  0 (0%)        0 (0%)      125Mi (7%)       0 (0%)         3h22m
  nginx-ingress              nginx-ingress-default-backend-67df647786-kx9nz    0 (0%)        0 (0%)      0 (0%)           0 (0%)         3h22m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                                          Requests      Limits
  --------                                          --------      ------
  cpu                                               652m (65%)    102m (10%)
  memory                                            1343Mi (85%)  100Mi (6%)
  ephemeral-storage                                 0 (0%)        0 (0%)
  attachable-volumes-csi-dobs.csi.digitalocean.com  0             0
Events:                                             <none>
```

**Comment by manics** [comment]
Kubernetes requires resources to run, as indicated by the error message your virtual machine has insufficient memory to run everything.

**Comment by chicocvenancio** [comment]
The image requests for 1GB ram and it seems no nodes have it available.

**Comment by JWDobken** [comment]
Ok thanks. Just for a test; I had 3 nodes with 2GB with 1 vCPU; which is apperently insufficient.
Increased the nodes to 8GB memory and 4vCPU and everything seems to work fine now.

So, I have been looking for minimum system requirements; they're not mentioned in the docs. I only found https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/40 without an answer.

I'll close this issue, thanks again. I might post some prometheus output later

**Comment by manics** [comment]
@jwdobken you're not the first person to run into problems with nodes that are too small. If you want to open a PR to improve the docs that'd be great! It doesn't have to be the minimum specs, just some guides on how to recognise you're too low on resources.
