### ISSUE TITLE
unable to validate against any pod security policy

### ISSUE THREAD

**Issue by misteliy** [jupyterhub/zero-to-jupyterhub-k8s#1386]
I was able to deploy with helm --version=0.7.0

```
NAMESPACE: jhub
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME        DATA  AGE
hub-config  36    2s

==> v1/Pod(related)
NAME                    READY  STATUS             RESTARTS  AGE
hub-557477f9b9-4pq4n    0/1    ContainerCreating  0         1s
proxy-7994bffbd5-nkczs  0/1    ContainerCreating  0         1s

==> v1/Secret
NAME        TYPE    DATA  AGE
hub-secret  Opaque  1     2s

==> v1/Service
NAME          TYPE          CLUSTER-IP      EXTERNAL-IP  PORT(S)       AGE
hub           ClusterIP     172.21.208.216  <none>       8081/TCP      2s
proxy-api     ClusterIP     172.21.116.124  <none>       8001/TCP      2s
proxy-public  LoadBalancer  172.21.62.25    <pending>    80:31386/TCP  1s

==> v1/ServiceAccount
NAME  SECRETS  AGE
hub   1        2s

==> v1beta1/PodDisruptionBudget
NAME   MIN AVAILABLE  MAX UNAVAILABLE  ALLOWED DISRUPTIONS  AGE
hub    1              N/A              0                    2s
proxy  1              N/A              0                    2s

==> v1beta1/Role
NAME  AGE
hub   2s

==> v1beta1/RoleBinding
NAME  AGE
hub   2s

==> v1beta2/Deployment
NAME   READY  UP-TO-DATE  AVAILABLE  AGE
hub    0/1    1           0          1s
proxy  0/1    1           0          1s
```

But run into following problem (log):

```
[E 2019-09-03 15:32:51.374 JupyterHub gen:974] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py:619> exception=ApiException()> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 970, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 626, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 486, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 406, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1703, in _start
        pod,
      File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1489, in asynchronize
        return method(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 6057, in create_namespaced_pod
        (data) = self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 6142, in create_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
        _request_timeout=_request_timeout)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 364, in request
        body=body)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 266, in POST
        body=body)
      File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 222, in request
        raise ApiException(http_resp=r)
    kubernetes.client.rest.ApiException: (403)
    Reason: error
    HTTP response headers: HTTPHeaderDict({'Audit-Id': '20394af0-2947-47df-a851-27ba9f230032', 'Content-Type': 'application/json', 'Date': 'Tue, 03 Sep 2019 15:32:50 GMT', 'Content-Length': '252'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"jupyter-user\" is forbidden: unable to validate against any pod security policy: []","reason":"Forbidden","details":{"name":"jupyter-user","kind":"pods"},"code":403}
```
Everything was deployed on AWS EC2 and I assume there must be a problem with the Role and RoleBindings, right?

**Comment by misteliy** [comment]
apparently this is related to Kubernetes Pod Security Policy which is enabled in our cluster.

**Comment by RAbraham** [comment]
@misteliy  how did you solve this issue?
