### ISSUE TITLE
Azure Active Directory auth not working

### ISSUE THREAD

**Issue by hugoespinelli** [jupyterhub/zero-to-jupyterhub-k8s#1604]
Hello!

My config.yaml is pretty simple:

```
auth:
  type: azuread
  azuread:
    clientId: my_client
    clientSecret: my_client_secret
    tenantId: my_tenantId
    callbackUrl: my_callback_url

proxy:
  secretToken: "my_token"
```

I can't spawn jupyter on kubernetes. I'm using GKE (Google Cloud Kubernetes).
If i remove auth, it works perfectly.

NAME                     READY   STATUS             RESTARTS   AGE
hub-7b5bd76cdc-n5c9t     0/1     CrashLoopBackOff   5          5m38s

This is the log of this pod.
```
Loading /etc/jupyterhub/config/values.yaml
Loading /etc/jupyterhub/secret/values.yaml
[E 2020-03-19 18:48:18.800 JupyterHub app:1958]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1955, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1639, in initialize
        self.load_config_file(self.config_file)
      File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-5>", line 2, in load_config_file
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 598, in load_config_file
        raise_config_file_errors=self.raise_config_file_errors,
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.6/dist-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/srv/jupyterhub_config.py", line 331, in <module>
        raise ValueError("Unhandled auth type: %r" % auth_type)
    ValueError: Unhandled auth type: 'azuread'

```
It's seems that azuread is not being recognizable. 
I'm following this tutorial:
https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html#azure-active-directory

I just copy and pasted yaml and added my credentials. 

Anybody know how to fix it?

Thanks!

**Comment by consideRatio** [comment]
Try specifying `--version 0.9.0-beta.4` when you run `helm upgrade`!

**Comment by hugoespinelli** [comment]
It works! Thanks!!
