### ISSUE TITLE
Hub pod is going into CrashLoopBackOff state after deployment

### ISSUE THREAD

**Issue by Abhi3linku** [jupyterhub/zero-to-jupyterhub-k8s#1675]
As soon as I deploy the Jupyterhub I can see the hub pod is going into the CrashLoopBackOff state with the below error:

Error:
kubectl logs hub-6569fdfd66-dpst5 -n jhub
Loading /etc/jupyterhub/config/values.yaml
Loading /etc/jupyterhub/secret/values.yaml
Loading extra config: environmentConfig
[E 2020-05-20 11:50:00.684 JupyterHub app:1958]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1955, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1639, in initialize
        self.load_config_file(self.config_file)
      File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-5>", line 2, in load_config_file
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 598, in load_config_file
        raise_config_file_errors=self.raise_config_file_errors,
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.6/dist-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/srv/jupyterhub_config.py", line 458, in <module>
        exec(config_py)
      File "<string>", line 15
        from subprocess import check_call
        ^
    IndentationError: unexpected indent

I am using the below command to deploy my jupyterhub using the below command
command: "helm upgrade --install jhub jupyterhub/jupyterhub --namespace jhub  --version=0.8.2 --values secret-config.yaml --values config.yaml"
I am using Kubernetes 1.17.0 and tested with the 1.18.2 version as well. Getting the same error.
I am  using BareMetal . I have checked the below issue (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/493) but could not figure it out what has to be done to fix this issue. Are we only certifying till 1.16 version?(Sorry If I misunderstood the comments/fix provided for the issue 493.). Any help/suggestion would be much appreciated! Thanks!

**Comment by Abhi3linku** [comment]
Closing this issue as its due to faulty piece of code included as part of config.yaml file. Hence this is no longer an issue and closing the same.
