### ISSUE TITLE
500 Internal Server Error with Ingress

### ISSUE THREAD

**Issue by drew-simmons** [jupyterhub/zero-to-jupyterhub-k8s#1749]
juypterhub.example.com returns:

500 : Internal Server Error
("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

```
hub:
  networkPolicy:
    enabled: true

proxy:
  secretToken: ""
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  https:
    enabled: false
    hosts:
      - "jupyterhub.example.dev"
    type: secret
    secret:
      name: jupyterhub-tls
  networkPolicy:
    enabled: true

auth:
  type: dummy

singleuser:
  networkPolicy:
    enabled: true

ingress:
  enabled: true
  hosts:
  - jupyterhub.example.com
  annotations:
    certmanager.k8s.io/cluster-issuer: ca-issuer
    kubernetes.io/ingress.class: traefik
  tls:
  - secretName: jupyterhub-tls
    hosts:
    - jupyterhub.example.com
```

Hub Logs show: 
```
[D 2020-08-21 20:00:58.770 JupyterHub user:242] Creating <class 'PatchedKubeSpawner'> for admin:
2020-08-21 20:00:58,779 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
2020-08-21 20:00:58,782 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
2020-08-21 20:00:58,785 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
[E 2020-08-21 20:00:58.790 JupyterHub web:1792] Uncaught exception GET /hub/ (10.10.0.1)
    HTTPServerRequest(protocol='http', host='jupyterhub.example.com', method='GET', uri='/hub/', version='HTTP/1.1', remote_ip='10.10.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 1701, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/handlers/pages.py", line 46, in get
        url = self.get_next_url(user)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 649, in get_next_url
        if user.spawner.active:
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/user.py", line 293, in spawner
        return self.spawners['']
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/user.py", line 140, in __getitem__
        self[key] = self.spawner_factory(key)
      File "/usr/local/lib/python3.6/site-packages/jupyterhub/user.py", line 286, in _new_spawner
        spawner = spawner_class(**spawn_kwargs)
      File "/usr/local/lib/python3.6/site-packages/kubespawner/spawner.py", line 182, in __init__
        self._start_watching_pods()
      File "/usr/local/lib/python3.6/site-packages/kubespawner/spawner.py", line 1718, in _start_watching_pods
        return self._start_reflector("pods", PodReflector, replace=replace)
      File "/usr/local/lib/python3.6/site-packages/kubespawner/spawner.py", line 1682, in _start_reflector
        **kwargs,
      File "/usr/local/lib/python3.6/site-packages/kubespawner/reflector.py", line 142, in __init__
        self.start()
      File "/usr/local/lib/python3.6/site-packages/kubespawner/reflector.py", line 291, in start
        self._list_and_update()
      File "/usr/local/lib/python3.6/site-packages/kubespawner/reflector.py", line 157, in _list_and_update
        _request_timeout=self.request_timeout,
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12372, in list_namespaced_pod
        (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 12472, in list_namespaced_pod_with_http_info
        collection_formats=collection_formats)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 334, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
        _request_timeout=_request_timeout)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 355, in request
        headers=headers)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
        query_params=query_params)
      File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 205, in request
        headers=headers)
      File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 76, in request
        method, url, fields=fields, headers=headers, **urlopen_kw
      File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 97, in request_encode_url
        return self.urlopen(method, url, **extra_kw)
      File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 330, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
        **response_kw
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
        **response_kw
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 760, in urlopen
        **response_kw
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.0.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
    
[D 2020-08-21 20:00:58.791 JupyterHub base:1197] No template for 500
[D 2020-08-21 20:00:58.791 JupyterHub user:242] Creating <class 'PatchedKubeSpawner'> for admin:
2020-08-21 20:00:58,798 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
2020-08-21 20:00:58,802 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/me-dev/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
2020-08-21 20:00:58,806 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server
[E 2020-08-21 20:00:58.812 JupyterHub log:166] {
      "X-Real-Ip": "10.10.0.1",
      "X-Forwarded-Server": "ingress-traefik",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "jupyterhub.example.com",
      "X-Forwarded-For": "",
      "Upgrade-Insecure-Requests": "1",
      "Te": "trailers",
      "Dnt": "1",
      "Cookie": "jupyterhub-hub-login=[secret]; traefik-session=[secret]; jupyterhub-session-id=[secret]",
      "Cache-Control": "max-age=0",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0",
      "Host": "jupyterhub.example.com",
      "Connection": "close"
    }

```

If Proxy is enabled with HTTPS; can't even get Login screen:
```
The page isn’t redirecting properly
An error occurred during a connection to jupyterhub.example.com.
    This problem can sometimes be caused by disabling or refusing to accept cookies.
```

**Comment by drew-simmons** [comment]
Correct. Proxy HTTPS is disabled, so getting error on redirect after successful log in with Dummy auth.
