### ISSUE TITLE
Cert acquisition instability in used Traefik versions

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1853]
## Cert aquisition
Apparently the instability with cert acquisition has surfaced again, which I think relates to Traefik v2.3.1 being released and us having pinned v2.3 rather than v2.3.0 for example. I reported an issue which i think has surfaced again, and was then mostly fixed by https://github.com/traefik/traefik/pull/6939.

An example of such recent error, can be seen in https://travis-ci.org/github/jupyterhub/zero-to-jupyterhub-k8s/jobs/737397758.

**Comment by consideRatio** [comment]
## Reopened as capp to hub api to start a user-server fail still
Here is the most recent failure with best error logs etc:
https://travis-ci.org/github/jupyterhub/zero-to-jupyterhub-k8s/jobs/737443531

The recurring theme is that the hub errors when speaking with the CHP proxy after the user has got a pod to represent it.

```
[I 2020-10-20 16:48:25.540 JupyterHub base:893] User testuser-aa6aa5ea-64bb-4719-93c7-04557f25c3d5 took 2.179 seconds to start
[I 2020-10-20 16:48:25.540 JupyterHub proxy:257] Adding user testuser-aa6aa5ea-64bb-4719-93c7-04557f25c3d5 to proxy /user/testuser-aa6aa5ea-64bb-4719-93c7-04557f25c3d5/ => http://192.168.79.75:8888
[D 2020-10-20 16:48:25.540 JupyterHub proxy:765] Proxy: Fetching POST http://proxy-api:8001/api/routes/user/testuser-aa6aa5ea-64bb-4719-93c7-04557f25c3d5
[I 2020-10-20 16:48:25.541 JupyterHub log:181] 200 GET /hub/api (@10.20.0.120) 1.70ms
[E 2020-10-20 16:48:25.542 JupyterHub base:915] Failed to add testuser-aa6aa5ea-64bb-4719-93c7-04557f25c3d5 to proxy!
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 908, in finish_user_spawn
        await self.proxy.add_user(user, server_name)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 270, in add_user
        await self.add_route(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 781, in add_route
        await self.api_request(path, method='POST', body=body)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 773, in api_request
        result = await client.fetch(req)
    tornado.curl_httpclient.CurlError: HTTP 599: Send failure: Broken pipe
```

If everything were as it should, the proxy should add a network route towards the newly added pod - it is a configurable proxy that JupyterHub controls after all.

```
16:48:18.515 [ConfigProxy] info: Adding route /user/testuser-c2521e10-e843-40c3-8cb6-dac422b1433a -> http://192.168.79.74:8888
```

But, it fail to do so, and doesn't seem to notice any incoming request to add a route, because it doesn't log any POST request.

**Comment by consideRatio** [comment]
## Cert acquisition intermittency issues
I'm debugging the cert acquisition intermittency issues, and looking to spot if a specific version of traefik has them in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1857.

There are various reports about race conditions, and at this point I think the best course of action is to test the intermittency issues thoroughly, and then just choose and pin a traefik version before 0.10.0 release.
