### ISSUE TITLE
Failed to connect to Hub API at http://hub:8081/hub/hub/api

### ISSUE THREAD

**Issue by tirumerla** [jupyterhub/zero-to-jupyterhub-k8s#1916]
### Bug description
Hi Guys,

I’m running into this issue after single user pods spawns and trying to connect to hub which is running in a **different namespace than single user pods**.

[Doesn't this code](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/files/hub/jupyterhub_config.py#L91) needs to be `http://hub.<singleuser_pods_namespace>:8081/hub/hub/api`

#### Expected behaviour
Single user pods should connect to hub without issues.

#### Actual behaviour
```
[E 2020-11-17 00:45:06.093 SingleUserNotebookApp log:174] 500 GET /hub/user/tirumerla/oauth_callback?code=[secret]&state=[secret] (@172.30.12.179) 29.46ms
[E 2020-11-17 00:45:10.023 SingleUserNotebookApp singleuser:438] Failed to connect to my Hub at http://hub:8081/hub/hub/api (attempt 3/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 432, in check_hub_version
        resp = await client.fetch(self.hub_api_url)
      File "/opt/conda/lib/python3.6/site-packages/tornado/simple_httpclient.py", line 336, in run
        source_ip=source_ip,
      File "/opt/conda/lib/python3.6/site-packages/tornado/tcpclient.py", line 270, in connect
        addrinfo = await self.resolver.resolve(host, port, af)
      File "/opt/conda/lib/python3.6/site-packages/tornado/netutil.py", line 396, in resolve
        None, _resolve_addr, host, port, family
      File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.6/site-packages/tornado/netutil.py", line 379, in _resolve_addr
        addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
      File "/opt/conda/lib/python3.6/socket.py", line 745, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -2] Name or service not known
[E 2020-11-17 00:45:18.035 SingleUserNotebookApp singleuser:438] Failed to connect to my Hub at http://hub:8081/hub/hub/api (attempt 4/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 432, in check_hub_version
        resp = await client.fetch(self.hub_api_url)
      File "/opt/conda/lib/python3.6/site-packages/tornado/simple_httpclient.py", line 336, in run
        source_ip=source_ip,
      File "/opt/conda/lib/python3.6/site-packages/tornado/tcpclient.py", line 270, in connect
        addrinfo = await self.resolver.resolve(host, port, af)
      File "/opt/conda/lib/python3.6/site-packages/tornado/netutil.py", line 396, in resolve
        None, _resolve_addr, host, port, family
      File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.6/site-packages/tornado/netutil.py", line 379, in _resolve_addr
        addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
      File "/opt/conda/lib/python3.6/socket.py", line 745, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -2] Name or service not known
[E 2020-11-17 00:45:34.048 SingleUserNotebookApp singleuser:438] Failed to connect to my Hub at http://hub:8081/hub/hub/api (attempt 5/5). Is it running?
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 432, in check_hub_version
        resp = await client.fetch(self.hub_api_url)
      File "/opt/conda/lib/python3.6/site-packages/tornado/simple_httpclient.py", line 336, in run
        source_ip=source_ip,
      File "/opt/conda/lib/python3.6/site-packages/tornado/tcpclient.py", line 270, in connect
        addrinfo = await self.resolver.resolve(host, port, af)
      File "/opt/conda/lib/python3.6/site-packages/tornado/netutil.py", line 396, in resolve
        None, _resolve_addr, host, port, family
      File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.6/site-packages/tornado/netutil.py", line 379, in _resolve_addr
        addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
      File "/opt/conda/lib/python3.6/socket.py", line 745, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -2] Name or service not known
```

### How to reproduce

Deploy Jupyterhub pods in "A" namespace and singleuser pods in "B" namespace using `c.KubeSpawner.namespace = 'B'`
You will see - `Failed to connect to Hub API at 'http://hub:8081/hub/hub/api'.  Is the Hub accessible at this URL`

### Your personal set up

Helm chart version: `0.10.2`
K8s version: `eks v1.17`
Jupyterhub version: `1.1.0`

[Posted on discourse](https://discourse.jupyter.org/t/500-failed-to-connect-to-my-hub-at-http-hub-8081-hub-hub-api/6785) as well.

**Comment by consideRatio** [comment]
Closing this in favor of the discourse post as it isn't a bug given that we don't support this feature in the Helm chart or kubespawner yet. I'll provide some input brief input there.
