### ISSUE TITLE
new version ldap can't work with error "automatic start_tls befored bind not successful"

### ISSUE THREAD

**Issue by evenye** [jupyterhub/zero-to-jupyterhub-k8s#1928]
### Bug description
new version  10.6 ldap can't work with error "automatic start_tls befored bind not successful"
but working well for 0.9.1 version

### Your personal set up

 - OS:
 
 - Version:
 
 - Configuration:

**Comment by evenye** [comment]
Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/login.py", line 144, in post
        user = await self.login_user(data)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 747, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/auth.py", line 459, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.8/dist-packages/ldapauthenticator/ldapauthenticator.py", line 382, in authenticate
        conn = self.get_connection(userdn, password)
      File "/usr/local/lib/python3.8/dist-packages/ldapauthenticator/ldapauthenticator.py", line 314, in get_connection
        conn = ldap3.Connection(
      File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 356, in __init__
        self._do_auto_bind()
      File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 391, in _do_auto_bind
        raise LDAPStartTLSError(error)
    ldap3.core.exceptions.LDAPStartTLSError: automatic start_tls befored bind not successful

**Comment by consideRatio** [comment]
This is not enough grounds to assume it is an issue of the JupyterHub Helm chart, so it may be caused by the the https://github.com/jupyterhub/ldapauthenticator which is installed in the hub pod, which has updated from version 1.3.0 to 1.3.2.
