### ISSUE TITLE
LDAP authentication fails due to unsupported protocol

### ISSUE THREAD

**Issue by nicholasmireles** [jupyterhub/zero-to-jupyterhub-k8s#1935]
### Bug description
When using the LDAP authentication method, users fail to authenticate due to an exception raised in the LDAP library.

#### Expected behaviour
At the login screen, a user would successfully or unsuccessfully be authenticated via LDAP

#### Actual behaviour
The user is presented with `500 : Internal Server Error` and the server shows an exception in the log.

### How to reproduce
helm install the jupyterhub/jupyterhub chart with the following configuration

```
  type: ldap
  ldap:
    server:
      address: LDAP_SERVER
      ssl: true | false
    dn: 
      templates:
        - 'DN_STRING`
```

### Your personal set up
 - OS: ubuntu 20.04
 - Version(s):
    - Helm verson: 3.4.1
    - Chart:  jupyterhub-0.10.6
    - Kubernetes version: 1.18.9

<details><summary>Configuration</summary>
```
  type: ldap
  ldap:
    server:
      address: LDAP_SERVER
      ssl: true | false
    dn: 
      templates:
        - 'DN_STRING`
```
</details>

<details><summary>Logs</summary>
```
Traceback (most recent call last):      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute        result = await result      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/login.py", line 144, in post        user = await self.login_user(data)      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 747, in login_user        authenticated = await self.authenticate(data)      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/auth.py", line 459, in get_authenticated_user        authenticated = await maybe_future(self.authenticate(handler, data))      File "/usr/local/lib/python3.8/dist-packages/ldapauthenticator/ldapauthenticator.py", line 382, in authenticate        conn = self.get_connection(userdn, password)      File "/usr/local/lib/python3.8/dist-packages/ldapauthenticator/ldapauthenticator.py", line 314, in get_connection        conn = ldap3.Connection(      File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 356, in __init__        self._do_auto_bind()      File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 380, in _do_auto_bind        self.open(read_server_info=False)      File "/usr/local/lib/python3.8/dist-packages/ldap3/strategy/sync.py", line 56, in open        BaseStrategy.open(self, reset_usage, read_server_info)
File "/usr/local/lib/python3.8/dist-packages/ldap3/strategy/base.py", line 145, in open        raise exception_history[0][0]    ldap3.core.exceptions.LDAPSocketOpenError: ("('socket ssl wrapping error: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1123)',)",)
```
</details>

**Comment by Gabrielvon** [comment]
Hey, @nicholasmireles. Have you found any solutions for this issue? I come across exactly same error. 

Thanks!
