### ISSUE TITLE
Mismatched helm chart versions

### ISSUE THREAD

**Issue by arokem** [jupyterhub/zero-to-jupyterhub-k8s#1958]
### Bug description

Versions of helm charts are mismatched on the page that first installs the chart (0.9.0):

https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html

and the page that shows how to upgrade the configuration (0.8.2):

https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/extending-jupyterhub.html

I believe that this can have some rather unfortunate consequences, when trying to upgrade the configuration. 

In particular, I get this error: 

```
➜  kubectl get pod --namespace $NAMESPACE
NAME                     READY   STATUS             RESTARTS   AGE
hub-7f64886954-n8phz     0/1     CrashLoopBackOff   6          11m
proxy-77dfb66845-gg8gl   1/1     Running            0          11m
➜  kubectl logs hub-7f64886954-n8phz     
Loading /etc/jupyterhub/config/values.yaml
Loading /etc/jupyterhub/secret/values.yaml
[I 2020-12-21 22:25:53.684 JupyterHub app:1673] Using Authenticator: oauthenticator.github.GitHubOAuthenticator-0.8.0
[I 2020-12-21 22:25:53.684 JupyterHub app:1673] Using Spawner: kubespawner.spawner.KubeSpawner
[I 2020-12-21 22:25:53.685 JupyterHub app:1016] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[I 2020-12-21 22:25:53.699 JupyterHub dbutil:125] Upgrading sqlite:///jupyterhub.sqlite
[I 2020-12-21 22:25:53.700 JupyterHub dbutil:105] Backing up jupyterhub.sqlite => jupyterhub.sqlite.2020-12-21-222553
[I 2020-12-21 22:25:54.202 alembic.runtime.migration migration:130] Context impl SQLiteImpl.
[I 2020-12-21 22:25:54.203 alembic.runtime.migration migration:137] Will assume non-transactional DDL.
FAILED: Can't locate revision identified by '4dc2d5a8c53c'
[E 2020-12-21 22:25:54.207 alembic.util.messaging messaging:60] Can't locate revision identified by '4dc2d5a8c53c'
[E 2020-12-21 22:25:54.268 JupyterHub app:1958]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1955, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1680, in initialize
        self.init_db()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1073, in init_db
        dbutil.upgrade_if_needed(self.db_url, log=self.log)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/dbutil.py", line 130, in upgrade_if_needed
        upgrade(db_url)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/dbutil.py", line 89, in upgrade
        ['alembic', '-c', alembic_ini, 'upgrade', revision]
      File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['alembic', '-c', '/tmp/tmp3n17twak/alembic.ini', 'upgrade', 'head']' returned non-zero exit status 255.

```

#### Expected behaviour

I think this should be 0.9.0 in both places.

**Comment by consideRatio** [comment]
Excellent point, this relates to https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1952! We end up with trouble having hardcoded versions in docs
