### ISSUE TITLE
Readiness probe failure with hub pods

### ISSUE THREAD

**Issue by Dauliac** [jupyterhub/zero-to-jupyterhub-k8s#2116]
Hello, I have some problems with chart on k3s.

### Bug description

Not depending of my config,the hub container crash in fault of readiness or proxy.

#### Actual behaviour

Hub pod crash in fault of readiness probe: `kubectl describe pod-xxx`
```
 Readiness probe failed: Get "http://10.42.0.164:8081/hub/health": dial tcp 10.42.0.164:8081: connect: connection refused
```

Complete describe here:
```bash
kubectl describe pod -n jhub hub-5dc494576d-j6sjx
Name:         hub-5dc494576d-j6sjx
Namespace:    jhub
Priority:     0
Node:         kubernetes/192.168.1.10
Start Time:   Fri, 26 Mar 2021 11:08:21 +0100
Labels:       app=jupyterhub
              component=hub
              hub.jupyter.org/network-access-proxy-api=true
              hub.jupyter.org/network-access-proxy-http=true
              hub.jupyter.org/network-access-singleuser=true
              pod-template-hash=5dc494576d
              release=jhub
Annotations:  checksum/config-map: 799fcd660407228c66950fec38fbada2839f5b7010924cfeb0b647d30f538333
              checksum/secret: 79664df44f3d61b748a38bcc24bae90e118e6bdabb9a24b22eae452ed390a4df
Status:       Running
IP:           10.42.0.170
IPs:
  IP:           10.42.0.170
Controlled By:  ReplicaSet/hub-5dc494576d
Containers:
  hub:
    Container ID:  containerd://d0c9e5e8f7a55c6460f51535129a5ae821425f8158d353b0a1f548b72a82db04
    Image:         jupyterhub/k8s-hub:0.10.0
    Image ID:      docker.io/jupyterhub/k8s-hub@sha256:257823711aff21af7977ceccafba4a0c2ffb946b6bf430a68fe7a341c6d11dd0
    Port:          8081/TCP
    Host Port:     0/TCP
    Args:
      jupyterhub
      --config
      /etc/jupyterhub/jupyterhub_config.py
      --debug
    State:          Running
      Started:      Fri, 26 Mar 2021 11:08:56 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 26 Mar 2021 11:08:22 +0100
      Finished:     Fri, 26 Mar 2021 11:08:54 +0100
    Ready:          False
    Restart Count:  1
    Requests:
      cpu:      200m
      memory:   512Mi
    Readiness:  http-get http://:http/hub/health delay=0s timeout=1s period=2s #success=1 #failure=3
    Environment:
      PYTHONUNBUFFERED:        1
      HELM_RELEASE_NAME:       jhub
      POD_NAMESPACE:           jhub (v1:metadata.namespace)
      CONFIGPROXY_AUTH_TOKEN:  <set to the key 'proxy.token' in secret 'hub-secret'>  Optional: false
    Mounts:
      /etc/jupyterhub/config/ from config (rw)
      /etc/jupyterhub/jupyterhub_config.py from config (rw,path="jupyterhub_config.py")
      /etc/jupyterhub/secret/ from secret (rw)
      /etc/jupyterhub/z2jh.py from config (rw,path="z2jh.py")
      /var/run/secrets/kubernetes.io/serviceaccount from hub-token-wtvw4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      hub-config
    Optional:  false
  secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub-secret
    Optional:    false
  hub-token-wtvw4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub-token-wtvw4
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  40s                default-scheduler  Successfully assigned jhub/hub-5dc494576d-j6sjx to kubernetes
  Normal   Pulled     6s (x2 over 40s)   kubelet            Container image "jupyterhub/k8s-hub:0.10.0" already present on machine
  Normal   Created    5s (x2 over 39s)   kubelet            Created container hub
  Normal   Started    5s (x2 over 39s)   kubelet            Started container hub
  Warning  Unhealthy  1s (x18 over 37s)  kubelet            Readiness probe failed: Get "http://10.42.0.170:8081/hub/health": dial tcp 10.42.0.170:8081: connect: connection refused
```

Here Api logs:
```bash
kubectl logs -n jhub proxy-7f54c7c77b-5gjn6
09:32:16.831 [ConfigProxy] info: Adding route / -> http://hub:8081
09:32:16.836 [ConfigProxy] info: Proxying http://:::8000 to http://hub:8081
09:32:16.836 [ConfigProxy] info: Proxy API at http://:::8001/api/routes
09:32:16.838 [ConfigProxy] info: Route added / -> http://hub:8081
```

And here hub logs:
```
[D 2021-03-26 10:08:57.510 JupyterHub application:752] Loaded config file: /etc/jupyterhub/jupyterhub_config.py
[I 2021-03-26 10:08:57.537 JupyterHub app:2332] Running JupyterHub version 1.2.0
[I 2021-03-26 10:08:57.537 JupyterHub app:2362] Using Authenticator: dummyauthenticator.dummyauthenticator.DummyAuthenticator
[I 2021-03-26 10:08:57.537 JupyterHub app:2362] Using Spawner: kubespawner.spawner.KubeSpawner-0.14.1
[I 2021-03-26 10:08:57.537 JupyterHub app:2362] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.2.0
[D 2021-03-26 10:08:57.538 JupyterHub app:1452] Generating new cookie_secret
[I 2021-03-26 10:08:57.538 JupyterHub app:1457] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[D 2021-03-26 10:08:57.538 JupyterHub app:1579] Connecting to db: sqlite://
[D 2021-03-26 10:08:57.548 JupyterHub orm:784] Stamping empty database with alembic revision 4dc2d5a8c53c
[I 2021-03-26 10:08:57.550 alembic.runtime.migration migration:155] Context impl SQLiteImpl.
[I 2021-03-26 10:08:57.550 alembic.runtime.migration migration:158] Will assume non-transactional DDL.
[I 2021-03-26 10:08:57.553 alembic.runtime.migration migration:517] Running stamp_revision  -> 4dc2d5a8c53c
[D 2021-03-26 10:08:57.553 alembic.runtime.migration migration:727] new branch insert 4dc2d5a8c53c
[W 2021-03-26 10:08:57.560 JupyterHub app:1687] No admin users, admin interface will be unavailable.
[W 2021-03-26 10:08:57.560 JupyterHub app:1688] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2021-03-26 10:08:57.560 JupyterHub app:1717] Not using allowed_users. Any authenticated user will be allowed.
[D 2021-03-26 10:08:57.588 JupyterHub app:1869] Purging expired APITokens
[D 2021-03-26 10:08:57.589 JupyterHub app:1869] Purging expired OAuthAccessTokens
[D 2021-03-26 10:08:57.591 JupyterHub app:1869] Purging expired OAuthCodes
[D 2021-03-26 10:08:57.598 JupyterHub app:1996] Initializing spawners
[D 2021-03-26 10:08:57.599 JupyterHub app:2129] Loaded users:

[I 2021-03-26 10:08:57.599 JupyterHub app:2399] Initialized 0 spawners in 0.001 seconds
[I 2021-03-26 10:08:57.600 JupyterHub app:2611] Not starting proxy
[D 2021-03-26 10:08:57.600 JupyterHub proxy:766] Proxy: Fetching GET http://proxy-api:8001/api/routes
[W 2021-03-26 10:08:57.602 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:02.620 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:07.742 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:12.884 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:19.292 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:21.622 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[W 2021-03-26 10:09:28.174 JupyterHub proxy:785] api_request to the proxy failed with status code 599, retrying...
[E 2021-03-26 10:09:28.174 JupyterHub app:2844]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2842, in launch_instance_async
        await self.start()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2615, in start
        await self.proxy.get_all_routes()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 832, in get_all_routes
        resp = await self.api_request('', client=client)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/proxy.py", line 796, in api_request
        result = await exponential_backoff(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 179, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Repeated api_request to proxy path "" failed.
```

If I manually edit the deployment and if I remove `readinessProbe` the hub pod keep crashing with strange failmount problem:
```bash
kubectl describe pod -n jhub hub-78ddfd467d-5nbxk
Name:         hub-78ddfd467d-5nbxk
Namespace:    jhub
Priority:     0
Node:         kubernetes/192.168.1.10
Start Time:   Fri, 26 Mar 2021 10:59:32 +0100
Labels:       app=jupyterhub
              component=hub
              hub.jupyter.org/network-access-proxy-api=true
              hub.jupyter.org/network-access-proxy-http=true
              hub.jupyter.org/network-access-singleuser=true
              pod-template-hash=78ddfd467d
              release=jhub
Annotations:  checksum/config-map: 799fcd660407228c66950fec38fbada2839f5b7010924cfeb0b647d30f538333
              checksum/secret: c958996ce32d385b4ff3aac97a843515bb2bc5dd5d4c79fbd25c6bc8c4e1e3e7
Status:       Running
IP:           10.42.0.165
IPs:
  IP:           10.42.0.165
Controlled By:  ReplicaSet/hub-78ddfd467d
Containers:
  hub:
    Container ID:  containerd://07ae27874952b4a5e13684b25ccb218485b601d925d8b67d423e6c896cbf1f54
    Image:         jupyterhub/k8s-hub:0.10.0
    Image ID:      docker.io/jupyterhub/k8s-hub@sha256:257823711aff21af7977ceccafba4a0c2ffb946b6bf430a68fe7a341c6d11dd0
    Port:          8081/TCP
    Host Port:     0/TCP
    Args:
      jupyterhub
      --config
      /etc/jupyterhub/jupyterhub_config.py
      --upgrade-db
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 26 Mar 2021 11:01:57 +0100
      Finished:     Fri, 26 Mar 2021 11:02:29 +0100
    Ready:          False
    Restart Count:  3
    Requests:
      cpu:     200m
      memory:  512Mi
    Environment:
      PYTHONUNBUFFERED:        1
      HELM_RELEASE_NAME:       jhub
      POD_NAMESPACE:           jhub (v1:metadata.namespace)
      CONFIGPROXY_AUTH_TOKEN:  <set to the key 'proxy.token' in secret 'hub-secret'>  Optional: false
    Mounts:
      /etc/jupyterhub/config/ from config (rw)
      /etc/jupyterhub/jupyterhub_config.py from config (rw,path="jupyterhub_config.py")
      /etc/jupyterhub/secret/ from secret (rw)
      /etc/jupyterhub/z2jh.py from config (rw,path="z2jh.py")
      /srv/jupyterhub from hub-db-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hub-token-xn5dh (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      hub-config
    Optional:  false
  secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub-secret
    Optional:    false
  hub-db-dir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  hub-db-dir
    ReadOnly:   false
  hub-token-xn5dh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub-token-xn5dh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    3m35s                default-scheduler  Successfully assigned jhub/hub-78ddfd467d-5nbxk to kubernetes
  Warning  FailedMount  3m35s                kubelet            MountVolume.SetUp failed for volume "hub-token-xn5dh" : failed to sync secret cache: timed out waiting for the condition
  Normal   Pulled       71s (x4 over 3m34s)  kubelet            Container image "jupyterhub/k8s-hub:0.10.0" already present on machine
  Normal   Created      71s (x4 over 3m34s)  kubelet            Created container hub
  Normal   Started      71s (x4 over 3m34s)  kubelet            Started container hub
  Warning  BackOff      10s (x6 over 2m23s)  kubelet            Back-off restarting failed container
```

### How to reproduce

I just run documentation command line with helm.
```bash
helm upgrade --cleanup-on-fail   --install $RELEASE jupyterhub/jupyterhub   --namespace $NAMESPACE   --create-namespace   --version=0.10.6   --values values.yaml
```

I also tried with `0.10.0` version and I have the same behavior.

`values.yaml`:
```yaml
auth:
  type: dummy
  dummy:
    password: admin Password
    admin:
      users:
        - admin
hub:
  # baseUrl: jhub.ubiwan.local
  admin_access: true
  db:
    type: sqlite-memory
  admin_users:
    - admin
  service:
    type: ClusterIP
# proxy relates to the proxy pod, the proxy-public service, and the autohttps
# pod and proxy-http service.
proxy:
  secretToken: 4cdc4d0d6927c5f4da9412f25c427cf3b43e858b3a611865e622272a3b986e1c
  # service relates to the proxy-public service
  https:
    enabled: true
  service:
    type: ClusterIP
```

### Your personal set up
I'm on k3s new cluster using default storageclass `local-storage`.
- My helm version:
  ```
   version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
  ```

**Comment by chrisbulgaria** [comment]
Hmm I have seen something very similar (hub logs) on one of my clusters with Jupyterhub recently ... coincidence ? Not troubleshooted yet- do you have any network policies preventing communication between pods or with k8s APi ? Running calico ( there was some similar issue with calico a while ago , don’t find it yet)? If running calico , any errors in controller log ? 

Chris

**Comment by consideRatio** [comment]
This is an error that would be caught in tests if it was related to the Helm chart I think. Note that we also use k3s there, but it can be started in various ways, and I think what makes it fail relates to that initial setup with regards to networking.

That was also the solution for the same issue posted in the Discourse forum as linked by @chrisbulgaria. Thank you for connecting this issue to that post @chrisbulgaria!

I'll go ahead and close this as as unrelated to this Helm chart but rather related to the k8s cluster setup.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/kubernetes-api-request-to-the-proxy-failed-with-status-code-599-retrying/8018/8

**Comment by Ursanon** [comment]
Strange, but installing version `1.1.3` without any cluster network 'fun' solved my issue.

**Comment by agelosnm** [comment]
This error happens everytime I deploy a new docker image for the users. 

I do have "flannel" installed in my k8s cluster so I cannot be sure whether is related to the networking or not, but one assumption I have is that my worker nodes have low storage for the size of the docker images we use (~20GB per image) and as a result "DiskPressure" comes up to a node. 
What I do is waiting for the image to be pulled by the cluster and terminate all users pods. Then I delete (restart) the hub pod and everything is fine!

I am planning a general maintenance of the system in the next days in order to have this resolved but I wanted to mention it for anyone else that may facing it.

**Comment by csawtelle** [comment]
`I do have "flannel" installed in my k8s cluster so I cannot be sure whether is related to the networking or not, but one assumption I have is that my worker nodes have low storage for the size of the docker images we use (~20GB per image) and as a result "DiskPressure" comes up to a node.`

I have these exact symptoms. Were you able to solve it? Was it an issue with Flannel? I reverted back to the original docker container but it won't recover.

**Comment by agelosnm** [comment]
> `I do have "flannel" installed in my k8s cluster so I cannot be sure whether is related to the networking or not, but one assumption I have is that my worker nodes have low storage for the size of the docker images we use (~20GB per image) and as a result "DiskPressure" comes up to a node.`
> 
> I have these exact symptoms. Were you able to solve it? Was it an issue with Flannel? I reverted back to the original docker container but it won't recover.

I performed upgrades in several components of my Jupyterhub infra. OS upgrades, k8s upgrades, Flannel upgrades & Jupyterhub upgrades. Also I gave more disk space to my nodes and the issue has not come back. I'm not sure which "components" have fixed the issue but since I had "DiskPressure" I think that adding more disk space to the nodes is the most major one.

**Comment by WhiteCat6142** [comment]
Coredns might affect it.
Please check it working correctly.

**Comment by mfreeman451** [comment]
I needed to restart coredns to get this to work, using jupyterhub 3.3.7 and calico
