### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by sajanraj** [jupyterhub/zero-to-jupyterhub-k8s#2282]
### Bug description
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
error in pod hub-...

### Your personal set up
followed instructions from here
https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html
 - OS:
  ubuntu 20.04,

 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
helm install jupyterhub jupyterhub-1.0.0/jupyterhub --values=jupyterhub.yaml
## modified yaml of jupyterhub
proxy:
  secretToken: "e3a9833dbe73925d092514320"

.......
  db:
    type: sqlite-pvc
    upgrade:
    pvc:
      annotations: {}
      selector: {}
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      subPath:
      storageClassName: local-storage
.....
NAME                                  READY   STATUS             RESTARTS   AGE
pod/continuous-image-puller-g4srp     1/1     Running            0          9h
pod/discovery                         0/1     Evicted            0          46d
pod/hub-7d9868b8cf-cqp4c              0/1     CrashLoopBackOff   114        9h
pod/postgres-5c7489f58-vckph            1/1     Running            1          3d20
...
$ kubectl get sc
NAME                      PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-storage (default)   kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false 
....
$ kubectl get pv
NAME            CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                  STORAGECLASS    REASON   AGE
local-storage   10Gi       RWO            Retain           Bound    default/hub-db-dir     local-storage  
...
$ kubectl get pvc
NAME           STATUS   VOLUME          CAPACITY   ACCESS MODES   STORAGECLASS    AGE
hub-db-dir     Bound    local-storage   10Gi       RWO            local-storage   9h

```
</details>

- <details><summary>Logs</summary>

```
Loading /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
[I 2021-06-24 18:28:13.536 JupyterHub app:2463] Running JupyterHub version 1.4.1
[I 2021-06-24 18:28:13.536 JupyterHub app:2493] Using Authenticator: jupyterhub.auth.DummyAuthenticator-1.4.1
[I 2021-06-24 18:28:13.536 JupyterHub app:2493] Using Spawner: kubespawner.spawner.KubeSpawner-1.0.0
[I 2021-06-24 18:28:13.537 JupyterHub app:2493] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-1.4.1
[E 2021-06-24 18:28:13.546 JupyterHub app:2973]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2970, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2505, in initialize
        self.init_db()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 1703, in init_db
        dbutil.upgrade_if_needed(self.db_url, log=self.log)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/dbutil.py", line 112, in upgrade_if_needed
        orm.check_db_revision(engine)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/orm.py", line 771, in check_db_revision
        current_table_names = set(inspect(engine).get_table_names())
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/inspection.py", line 64, in inspect
        ret = reg(subject)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/reflection.py", line 182, in _engine_insp
        return Inspector._construct(Inspector._init_engine, bind)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/reflection.py", line 117, in _construct
        init(self, bind)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/reflection.py", line 128, in _init_engine
        engine.connect().close()
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3096, in connect
        return self._connection_cls(self, close_with_result=close_with_result)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 92, in __init__
        else engine.raw_connection()
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3175, in raw_connection
        return self._wrap_pool_connect(self.pool.connect, _connection)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
        Connection._handle_dbapi_exception_noconnection(
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
        util.raise_(
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
        raise exception
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3142, in _wrap_pool_connect
        return fn()
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 301, in connect
        return _ConnectionFairy._checkout(self)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 761, in _checkout
        fairy = _ConnectionRecord.checkout(pool)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 419, in checkout
        rec = pool._do_get()
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
        return self._create_connection()
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
        return _ConnectionRecord(self)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 362, in __init__
        self.__connect()
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 605, in __connect
        pool.logger.debug("Error on connect(): %s", e)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
        compat.raise_(
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
        raise exception
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 599, in __connect
        connection = pool._invoke_creator(self)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 578, in connect
        return dialect.connect(*cargs, **cparams)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 584, in connect
        return self.dbapi.connect(*cargs, **cparams)
    sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
    (Background on this error at: http://sqlalche.me/e/14/e3q8)

```
</details>

**Comment by consideRatio** [comment]
What does your Helm chart configuration look like, and what version did you install? Latest chart version is 1.0.0, which is what you installed if you didn't explicitly declare a version.

**Comment by sajanraj** [comment]
updated the issue with more details , please have a look.

**Comment by consideRatio** [comment]
I would debug this by changing hub.db.type to sqlite-memory and then

kubectl exec -it deploy/hub /bin/bash

Then inspect permissions of the file system where the mount is. I guess that the mounted file system folder have root permissions etc or similar. Can you check?

I believe you can find the location of the mount by inspecting the hub pods YAML file

**Comment by sajanraj** [comment]
kubectl exec -it deploy/hub /bin/bash- this is not working in failed pods
# # deployement
```
kubectl get deploy/hub -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: jupyterhub
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-06-25T09:03:09Z"
  generation: 1
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-1.0.0
    component: hub
    heritage: Helm
    release: jupyterhub
  name: hub
  namespace: default
  resourceVersion: "5782415"
  uid: 61cad57a-c0e7-4de6-a59a-79bbe71363dd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jupyterhub
      component: hub
      release: jupyterhub
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config-map: dd8d4cefc688a80c72570f9008c065a11d0139289636ce0f063664ed723a39e1
        checksum/secret: 65e2938e8fc229f0b823638d760894b3463b9039925ca1f0c3cbbc5f186f7856
      creationTimestamp: null
      labels:
        app: jupyterhub
        component: hub
        hub.jupyter.org/network-access-proxy-api: "true"
        hub.jupyter.org/network-access-proxy-http: "true"
        hub.jupyter.org/network-access-singleuser: "true"
        release: jupyterhub
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: hub.jupyter.org/node-purpose
                operator: In
                values:
                - core
            weight: 100
      containers:
      - args:
        - jupyterhub
        - --config
        - /usr/local/etc/jupyterhub/jupyterhub_config.py
        - --upgrade-db
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: HELM_RELEASE_NAME
          value: jupyterhub
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONFIGPROXY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: hub.config.ConfigurableHTTPProxy.auth_token
              name: hub
        image: jupyterhub/k8s-hub:1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /hub/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: hub
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 1000
          httpGet:
            path: /hub/health
            port: http
            scheme: HTTP
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.py
          name: config
          subPath: jupyterhub_config.py
        - mountPath: /usr/local/etc/jupyterhub/z2jh.py
          name: config
          subPath: z2jh.py
        - mountPath: /usr/local/etc/jupyterhub/config/
          name: config
        - mountPath: /usr/local/etc/jupyterhub/secret/
          name: secret
        - mountPath: /srv/jupyterhub
          name: pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: hub
      serviceAccountName: hub
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: hub.jupyter.org/dedicated
        operator: Equal
        value: core
      - effect: NoSchedule
        key: hub.jupyter.org_dedicated
        operator: Equal
        value: core
      volumes:
      - configMap:
          defaultMode: 420
          name: hub
        name: config
      - name: secret
        secret:
          defaultMode: 420
          secretName: hub
      - name: pvc
        persistentVolumeClaim:
          claimName: hub-db-dir
status:
  conditions:
  - lastTransitionTime: "2021-06-25T09:03:11Z"
    lastUpdateTime: "2021-06-25T09:03:11Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2021-06-25T09:14:07Z"
    lastUpdateTime: "2021-06-25T09:14:07Z"
    message: ReplicaSet "hub-5685f48988" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1


```
## PVC and SC
I have created a storage class in local
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: local-storage
#provisioner: kubernetes.io/master-kmrl
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
#  name: local-storage
   name: hub-db-pv
spec:
  capacity:
    storage: 10Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/home/kmrl/kube"
```

**Comment by consideRatio** [comment]
> kubectl exec -it deploy/hub /bin/bash- this is not working in failed pods

@sajanraj yepp, but if you use hub.db.type=sqlite-memory, does it still fail?

**Comment by sajanraj** [comment]
@consideRatio It is working with hub.db.type=sqlite-memory. Connecting to storage goes wrong.

**Comment by consideRatio** [comment]
Try exec into the pod, and list folder permissions.

**Comment by sajanraj** [comment]
$ kubectl exec hub-5685f48988-7cg9r -it -- /bin/bash
error: unable to upgrade connection: container not found ("hub")

**Comment by consideRatio** [comment]
As you can see from the deploy/hub specifications, the `securityContext` has a `fsGroup: 1000` configuration. It is meant to help influence the permissions on mounted volumes etc. But, it doesn't have support for any kind of storage.

I think the issue can be summarized as:

1. You use a local-storage provider that you have defined yourself
2. Your storage provider doesn't support `fsGroup` configuration
3. The hub requires a mounted storage directory to be accessible as it would be if `fsGroup` was respected - but isn't.

I don't consider this to be an issue with this Helm chart, but a limitation on your default k8s storageclass setup. If you want to debug this, I suggest that you:

1. create a standalone pod that just run `sleep infinity` using the `busybox` image for example
2. let this pod declare volumes and volumeMounts like the hub pod did
3. let this pod have a pod securityContext with `fsGroup: 1000` just like the hub pod has
4. kubectl exec into the pod and `ls -alh` the mounted storage directory to inspect the permissions

I'll want to not invest more time in this issue as it turns out to be unrelated to the Helm chart, but now that it is a GitHub issue in this repo and others googling their way may want to understand the resolution - if you have time, please write some notes on the solution you go with in the end.

**Comment by sajanraj** [comment]
## fix  
all these are related to storage permission as you have noted. Anyway thank you! @consideRatio.
pods doesn't have permission at bound state.
```
chown 777 -R /home/kmrl/kube 
```
do this for sqldb and user data store.

this will fix, since pv store reference to this path.

**Comment by consideRatio** [comment]
Thanks for following up @sajanraj! Glad you sorted it out!
