### ISSUE TITLE
Fix jupyterhub-idle-culler's permissions

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2407]
I think we have failed to provide the permissions properly to jupyterhub-idle-culler somehow.

I observe the following in the hub logs after #2395 has merged. I figure this error can show if:
- jupyterhub/jupyterhub-idle-culler permission failure?
  The idle culler could be making a request to /hub/api/info without passing its token.
- Helm chart config failure.
  - We may have failed to pass permissions to the managed JupyterHub service.
    - Is the managed service coupled with a role granting it more permissions? Hmmm?
    - Is the role granting the service enough permissions? Yes.
- jupyterhub/jupyterhub permission failure?
  JupyterHub itself may fail somehow, for example with some race condition?

```
[W 2021-09-26 01:03:47.331 JupyterHub scopes:489] Not authorizing access to /hub/api/info. Requires any of [read:hub], not derived from scopes [read:servers, servers, list:users, read:users:activity, read:users:name]
[W 2021-09-26 01:03:47.331 JupyterHub web:1787] 403 GET /hub/api/info (127.0.0.1): Action is not authorized with current scopes; requires any of [read:hub]
[E 210926 01:03:47 ioloop:761] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f1a50e10af0>>, <Task finished name='Task-1' coro=<cull_idle() done, defined at /usr/local/lib/python3.8/dist-packages/jupyterhub_idle_culler/__init__.py:73> exception=HTTP 403: Forbidden>)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 741, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 765, in _discard_future_result
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub_idle_culler/__init__.py", line 164, in cull_idle
        resp = await fetch(HTTPRequest(url=url + "/info", headers=auth_header))
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub_idle_culler/__init__.py", line 117, in fetch
        return await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
```

**Comment by consideRatio** [comment]
The reason we need `read:hub` is because a version check via the hub api, [see this code](https://github.com/jupyterhub/jupyterhub-idle-culler/blob/ae59078ccf3f929702d9833b6b9e644dae0e191d/jupyterhub_idle_culler/__init__.py#L160-L167).
