### ISSUE TITLE
Spawn failed: Could not create pod jupyter-user1

### ISSUE THREAD

**Issue by nmarandi** [jupyterhub/zero-to-jupyterhub-k8s#2529]
### Bug description

cannot start the server after clicking on the start button.

#### Expected behavior

server starts normally after clicking on the start button.

#### Actual behaviour

![image](https://user-images.githubusercontent.com/34411083/147533743-5eb13421-ec7d-45ef-8943-72359f9b0ffd.png)

### How to reproduce

it's a fresh install with helm chart version 1.2.0 installed on Kubernetes

### Your personal set up

 - OS: ubuntu 20.04
 

- <details><summary>Configuration</summary>

```yaml
proxy:
  secretToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  https:
    enabled: true
    hosts:
      - www.w3schools.com
    type: secret
    secret:
      name: jupyterhub-tls
singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: lab-3.1.12
  extraEnv: 
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
  uid: 0
  defaultUrl: "/lab"
  storage:
    dynamic:
      storageClass: csi-cephfs-sc
      storageAccessModes: [ReadWriteMany]
  profileList:
    - display_name: "Minimal environment"
      description: "without gpu"
      memory:
        limit: 1G
        guarantee: 1G
      default: true
    - display_name: "Datascience environment"
      description: "with gpu"
      memory:
        limit: 1G
        guarantee: 1G
      kubespawner_override:
        extra_resource_limits:
          nvidia.com/gpu: "1"
hub:
  extraConfig:
    hub: |
      c.JupyterHub.tornado_settings = { "headers": { "Content-Security-Policy": "frame-ancestors 'self' https://www.w3schools.com:443"}}
    spawner: |
      c.Spawner.args = ['--allow-root','--NotebookApp.tornado_settings={"headers":{"Content-Security-Policy": "frame-ancestors * self https://www.w3schools.com:443"}}'] 
  config:
    Authenticator:
      auto_login: true
    GenericOAuthenticator:
      admin_users:
      - user1
      - user2
      client_id: jupyterhub
      client_secret: 
      oauth_callback_url:
      authorize_url: 
      token_url: 
      userdata_url:
      login_service: keycloak
      username_key: preferred_username
      userdata_params:
        state: state
    JupyterHub:
      authenticator_class: generic-oauth
      admin_access: true
  services:
    testService:
      admin: true
      apiToken: "xxxxxxx"

```
</details>

- <details><summary>Logs</summary>

hub pod logs:
```
[I 2021-12-28 06:03:47.356 JupyterHub log:189] 200 GET /hub/api/users/user1/server/progress (user1@192.168.18.20) 7.31ms
[I 2021-12-28 06:03:50.560 JupyterHub provider:574] Creating oauth client jupyterhub-user-user1
[I 2021-12-28 06:03:50.579 JupyterHub spawner:2344] Attempting to create pvc claim-user1, with timeout 3
[I 2021-12-28 06:03:50.598 JupyterHub spawner:2361] PVC claim-user1 already exists, so did not create new pvc.
[I 2021-12-28 06:03:50.600 JupyterHub spawner:2302] Attempting to create pod jupyter-user1, with timeout 3
[I 2021-12-28 06:03:51.535 JupyterHub log:189] 302 POST /hub/spawn -> /hub/spawn-pending/user1 (user1@192.168.18.20) 1008.39ms
[I 2021-12-28 06:03:51.585 JupyterHub pages:402] user1 is pending spawn
[I 2021-12-28 06:03:53.715 JupyterHub spawner:2302] Attempting to create pod jupyter-user1, with timeout 3
[I 2021-12-28 06:03:57.112 JupyterHub spawner:2302] Attempting to create pod jupyter-user1, with timeout 3
[I 2021-12-28 06:04:00.132 JupyterHub spawner:2302] Attempting to create pod jupyter-user1, with timeout 3
[W 2021-12-28 06:04:00.532 JupyterHub base:1008] User user1 is slow to start (timeout=10)
[E 2021-12-28 06:04:00.609 JupyterHub gen:623] Exception in Future <Future finished exception=ApiException()> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 618, in error_callback
        future.result()
      File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/spawner.py", line 2117, in asynchronize
        return method(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api/core_v1_api.py", line 7320, in create_namespaced_pod
        return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)  # noqa: E501
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api/core_v1_api.py", line 7415, in create_namespaced_pod_with_http_info
        return self.api_client.call_api(
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 348, in call_api
        return self.__call_api(resource_path, method,
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 180, in __call_api
        response_data = self.request(
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 391, in request
        return self.rest_client.POST(url,
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/rest.py", line 274, in POST
        return self.request("POST", url,
      File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/rest.py", line 233, in request
        raise ApiException(http_resp=r)
    kubernetes.client.exceptions.ApiException: (409)
    Reason: Conflict
    HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '66adedc6-4372-417b-886d-b6862ee17816', 'X-Kubernetes-Pf-Prioritylevel-Uid': '648d43ae-537f-458c-92b5-6dbf4ed46b86', 'Date': 'Tue, 28 Dec 2021 06:04:00 GMT', 'Content-Length': '204'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"jupyter-user1\" already exists","reason":"AlreadyExists","details":{"name":"jupyter-user1","kind":"pods"},"code":409}

[E 2021-12-28 06:04:23.862 JupyterHub user:718] Unhandled error starting user1's server: Could not create pod jupyter-user1
[W 2021-12-28 06:04:23.862 JupyterHub spawner:2103] Pod jupyter-user1 url changed! hub-55b456cc68-jcmvb:49147 -> 10.244.0.50:8888
[I 2021-12-28 06:04:23.888 JupyterHub spawner:2620] Deleting pod jupyter-user1
[W 2021-12-28 06:04:30.769 JupyterHub base:976] 2 consecutive spawns failed.  Hub will exit if failure count reaches 5 before succeeding
[E 2021-12-28 06:04:30.769 JupyterHub gen:623] Exception in Future <Task finished name='Task-550' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py:900> exception=TimeoutError('Could not create pod jupyter-user1')> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 618, in error_callback
        future.result()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 907, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 736, in spawn
        raise e
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/user.py", line 635, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.8/dist-packages/kubespawner/spawner.py", line 2508, in _start
        await exponential_backoff(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/utils.py", line 184, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Could not create pod jupyter-user1
    
[I 2021-12-28 06:04:30.769 JupyterHub log:189] 200 GET /hub/api/users/user1/server/progress (user1@192.168.18.20) 38897.15ms
[W 2021-12-28 06:04:35.792 JupyterHub log:189] 403 GET /hub/metrics (@10.244.1.1) 0.78ms
[I 2021-12-28 06:04:40.096 JupyterHub log:189] 200 GET /hub/api (@10.244.1.1) 1.71ms
[W 2021-12-28 06:04:40.177 JupyterHub log:189] 403 POST /hub/api/users/user1/activity (@10.244.1.1) 4.24ms
[W 2021-12-28 06:04:40.798 JupyterHub log:189] 403 POST /hub/api/users/user1/activity (@10.244.1.1) 1.28ms
[W 2021-12-28 06:04:41.782 JupyterHub log:189] 403 POST /hub/api/users/user1/activity (@10.244.1.1) 1.02ms
[W 2021-12-28 06:04:42.047 JupyterHub log:189] 403 POST /hub/api/users/user1/activity (@10.244.1.1) 0.97ms
[I 2021-12-28 06:04:44.101 JupyterHub log:189] 302 GET / -> /hub/ (@192.168.18.20) 0.43ms
[I 2021-12-28 06:04:44.196 JupyterHub log:189] 302 GET /hub/ -> /hub/spawn (user1@192.168.18.20) 4.63ms
[I 2021-12-28 06:04:44.288 JupyterHub log:189] 200 GET /hub/spawn (user1@192.168.18.20) 6.56ms
[W 2021-12-28 06:04:46.269 JupyterHub log:189] 403 POST /hub/api/users/user1/activity (@10.244.1.1) 0.96ms
```
jupyter-user1 pod logs 1:

```
[W 2021-12-28 06:06:18.864 SingleUserNotebookApp configurable:193] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2021-12-28 06:06:18.920 SingleUserNotebookApp notebookapp:1593] Authentication of /metrics is OFF, since other authentication is disabled.
[W 2021-12-28 06:06:19.817 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-28 06:06:19.817 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-28 06:06:19.817 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-28 06:06:19.817 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-28 06:06:19.817 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-12-28 06:06:19.830 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.9/site-packages/jupyterlab
[I 2021-12-28 06:06:19.830 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
Patching auth into jupyter_server.base.handlers.JupyterHandler(jupyter_server.base.handlers.AuthenticatedHandler) -> JupyterHandler(jupyterhub.singleuser.mixins.HubAuthenticatedHandler, jupyter_server.base.handlers.AuthenticatedHandler)
[I 2021-12-28 06:06:19.841 SingleUserNotebookApp mixins:576] Starting jupyterhub-singleuser server version 1.4.2
[W 2021-12-28 06:06:19.851 SingleUserNotebookApp _version:70] jupyterhub version 1.5.0 != jupyterhub-singleuser version 1.4.2. This could cause failure to authenticate and result in redirect loops!
[I 2021-12-28 06:06:19.852 SingleUserNotebookApp notebookapp:2302] Serving notebooks from local directory: /home/jovyan
[I 2021-12-28 06:06:19.852 SingleUserNotebookApp notebookapp:2302] Jupyter Notebook 6.4.4 is running at:
[I 2021-12-28 06:06:19.852 SingleUserNotebookApp notebookapp:2302] http://jupyter-user1:8888/user/user1/
[I 2021-12-28 06:06:19.852 SingleUserNotebookApp notebookapp:2303] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2021-12-28 06:06:19.937 SingleUserNotebookApp mixins:556] Updating Hub with activity every 300 seconds
[E 2021-12-28 06:06:19.942 SingleUserNotebookApp mixins:538] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 536, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2021-12-28 06:06:20.724 SingleUserNotebookApp mixins:538] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 536, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2021-12-28 06:06:20.870 SingleUserNotebookApp mixins:538] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 536, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2021-12-28 06:06:22.712 SingleUserNotebookApp mixins:538] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 536, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2021-12-28 06:06:24.933 SingleUserNotebookApp mixins:538] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 536, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2021-12-28 06:06:30.146 SingleUserNotebookApp mixins:538] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 536, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2021-12-28 06:06:45.166 SingleUserNotebookApp mixins:538] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 536, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2021-12-28 06:07:00.187 SingleUserNotebookApp mixins:538] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 536, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2021-12-28 06:07:15.209 SingleUserNotebookApp mixins:538] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 536, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2021-12-28 06:07:22.538 SingleUserNotebookApp mixins:538] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 536, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2021-12-28 06:07:22.538 SingleUserNotebookApp mixins:563] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 561, in keep_activity_updated
        await self.notify_activity()
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/singleuser/mixins.py", line 543, in notify_activity
        await exponential_backoff(
      File "/opt/conda/lib/python3.9/site-packages/jupyterhub/utils.py", line 184, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Failed to notify Hub of activity

```

jupyter-user1 pod logs 1:
```
[W 2021-12-28 06:44:06.827 SingleUserNotebookApp configurable:193] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2021-12-28 06:44:06.856 SingleUserNotebookApp notebookapp:1593] Authentication of /metrics is OFF, since other authentication is disabled.
[W 2021-12-28 06:44:07.701 LabApp] 'tornado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-28 06:44:07.702 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-28 06:44:07.702 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-28 06:44:07.702 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-12-28 06:44:07.702 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-12-28 06:44:07.712 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.9/site-packages/jupyterlab
[I 2021-12-28 06:44:07.712 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
Patching auth into jupyter_server.base.handlers.JupyterHandler(jupyter_server.base.handlers.AuthenticatedHandler) -> JupyterHandler(jupyterhub.singleuser.mixins.HubAuthenticatedHandler, jupyter_server.base.handlers.AuthenticatedHandler)
[I 2021-12-28 06:44:07.720 SingleUserNotebookApp mixins:576] Starting jupyterhub-singleuser server version 1.4.2
[W 2021-12-28 06:44:07.727 SingleUserNotebookApp _version:70] jupyterhub version 1.5.0 != jupyterhub-singleuser version 1.4.2. This could cause failure to authenticate and result in redirect loops!
[I 2021-12-28 06:44:07.728 SingleUserNotebookApp notebookapp:2302] Serving notebooks from local directory: /home/jovyan
[I 2021-12-28 06:44:07.728 SingleUserNotebookApp notebookapp:2302] Jupyter Notebook 6.4.4 is running at:
[I 2021-12-28 06:44:07.728 SingleUserNotebookApp notebookapp:2302] http://jupyter-user1:8888/user/user1/
[I 2021-12-28 06:44:07.728 SingleUserNotebookApp notebookapp:2303] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2021-12-28 06:44:07.799 SingleUserNotebookApp mixins:556] Updating Hub with activity every 300 seconds
[C 2021-12-28 06:44:17.150 SingleUserNotebookApp notebookapp:1972] received signal 15, stopping
[I 2021-12-28 06:44:17.173 SingleUserNotebookApp notebookapp:2139] Shutting down 0 kernels
[I 2021-12-28 06:44:17.178 SingleUserNotebookApp notebookapp:2154] Shutting down 0 terminals

```

</details>

**Comment by consideRatio** [comment]
Please ask a question for help like this in the discourse.jupyter.org forums!
