### ISSUE TITLE
Bug in z2jh.py merge_dictionaries helper function: breaks if either dictionary is None

### ISSUE THREAD

**Issue by BrendanPC** [jupyterhub/zero-to-jupyterhub-k8s#2587]
### Bug description
There is a helper function in [jupyterhub/files/hub/z2jh.py](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/files/hub/z2jh.py), _merge_dictionaries, which does not correctly handle None dictionaries.

At the top of the function, there should be a check:
```
if not b:
  return a.copy()
if not a:
  return b.copy()
```
to avoid iterating over None, but this is missing.

#### Expected behaviour
When passed a valid dictionary and a None dictionary, merge_dictionaries should return a copy of the valid dictionary, and not throw an error.

#### Actual behaviour
When one of the dictionaries is None, you get the error `TypeError: 'NoneType' object is not iterable`.

This is a confusing error because the cause is actually that one of your values.yaml files was not loaded correctly (or maybe for whatever reason is intentionally empty).

### How to reproduce

merge_dictionaries is used by load_config in the same file, which will create None dictionaries any time it tries to load an empty yaml. In the abstract, just call merge_dictionaries using a dictionary and None as one of the parameters.

### Your personal set up
Set up is not relevant, this is a simple Python bug, easily seen by inspecting the code.

- <details><summary>Logs</summary>

```
Loading /etc/jupyterhub/config/values.yaml
Loading /etc/jupyterhub/secret/values.yaml
[E 2022-02-07 22:27:40.801 JupyterHub app:2859]
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2856, in launch_instance_async
await self.initialize(argv)
File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2347, in initialize
self.load_config_file(self.config_file)
File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 87, in inner
return method(app, *args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 775, in load_config_file
for (config, filename) in self._load_config_files(filename, path=path, log=self.log,
File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 737, in _load_config_files
config = loader.load_config()
File "/usr/local/lib/python3.8/dist-packages/traitlets/config/loader.py", line 616, in load_config
self._read_file_as_dict()
File "/usr/local/lib/python3.8/dist-packages/traitlets/config/loader.py", line 648, in _read_file_as_dict
exec(compile(f.read(), conf_filename, 'exec'), namespace, namespace)
File "/etc/jupyterhub/jupyterhub_config.py", line 55, in <module>
db_type = get_config("hub.db.type")
File "/etc/jupyterhub/z2jh.py", line 58, in get_config
value = _load_config()
File "/etc/jupyterhub/z2jh.py", line 27, in _load_config
cfg = _merge_dictionaries(cfg, values)
File "/etc/jupyterhub/z2jh.py", line 39, in _merge_dictionaries
for key in b:
TypeError: 'NoneType' object is not iterable
```
</details>

**Comment by consideRatio** [comment]
Ah, so the situation is about this code.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/3c710c628f9c491b712a14e83cea9bd36a662ad6/jupyterhub/files/hub/z2jh.py#L14-L29

The assumption is that you have a dictionary at all in a values.yaml file declared in `hub.existingSecret`. Hmm... Can you redact and share a k8s Secret yaml that you have had that led to this error? Note that the base64 encoding you will find in k8s Secret's can be decoded by anyone - so you may need to first decode your content and then redact sensitive content with dummy data of the same kind.

While I'm 100% that we should at least fail with a more descriptive error - I'm not sure if it makes sense to error loudly provide a warning in this situation.

**Comment by BrendanPC** [comment]
Hi thanks, good point that avoiding the None dictionary situation altogether is another solution.

To clarify, I was not intentionally trying to use an empty values file, it was the result of the error in configuration, something like this:
`kubectl create secret generic example --from-literal=values.yaml=missing.yaml`

The error that eventually arose from this was confusing and distracted from the root cause, the missing values.yaml.
