### ISSUE TITLE
Failure of Service cull-idle

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#280]
I'm seeing regular errors in `Service cull-idle`.

`kubectl --namespace ebi-training log -f deployment/hub-deployment`:
```
[I 2017-11-17 10:07:56.450 JupyterHub app:830] Loading cookie_secret from env[JPY_COOKIE_SECRET]
[D 2017-11-17 10:07:56.451 JupyterHub app:886] Connecting to db: sqlite://
[D 2017-11-17 10:07:56.464 JupyterHub orm:475] Stamping empty database with alembic revision 3ec6993fe20c
[I 2017-11-17 10:07:56.470 alembic.runtime.migration migration:117] Context impl SQLiteImpl.
[I 2017-11-17 10:07:56.470 alembic.runtime.migration migration:122] Will assume non-transactional DDL.
[I 2017-11-17 10:07:56.472 alembic.runtime.migration migration:327] Running stamp_revision  -> 3ec6993fe20c
[D 2017-11-17 10:07:56.473 alembic.runtime.migration migration:516] new branch insert 3ec6993fe20c
[W 2017-11-17 10:07:56.483 JupyterHub app:955] No admin users, admin interface will be unavailable.
[W 2017-11-17 10:07:56.483 JupyterHub app:956] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2017-11-17 10:07:56.483 JupyterHub app:983] Not using whitelist. Any authenticated user will be allowed.
[D 2017-11-17 10:07:56.511 JupyterHub app:1241] Loaded users:
[I 2017-11-17 10:07:56.517 JupyterHub app:1528] Hub API listening on http://0.0.0.0:8081/ebi-training/hub/
[I 2017-11-17 10:07:56.517 JupyterHub app:1538] Not starting proxy
[I 2017-11-17 10:07:56.517 JupyterHub app:1544] Starting managed service cull-idle
[I 2017-11-17 10:07:56.518 JupyterHub service:266] Starting service 'cull-idle': ['/usr/local/bin/cull_idle_servers.py', '--timeout=3600', '--cull-every=600']
[I 2017-11-17 10:07:56.520 JupyterHub service:109] Spawning /usr/local/bin/cull_idle_servers.py --timeout=3600 --cull-every=600
[D 2017-11-17 10:07:56.523 JupyterHub spawner:727] Polling subprocess every 30s
[D 2017-11-17 10:07:56.525 JupyterHub proxy:552] Proxy: Fetching GET http://10.233.30.148:8001/api/routes
[D 2017-11-17 10:07:56.539 JupyterHub proxy:596] Omitting non-jupyterhub route '/'
[W 2017-11-17 10:07:56.540 JupyterHub proxy:304] Adding missing default route
[I 2017-11-17 10:07:56.540 JupyterHub proxy:370] Adding default route for Hub: / => http://10.233.43.255:8081
[D 2017-11-17 10:07:56.540 JupyterHub proxy:552] Proxy: Fetching POST http://10.233.30.148:8001/api/routes/
[I 2017-11-17 10:07:56.546 JupyterHub app:1581] JupyterHub is now running at http://10.233.41.86:80/ebi-training/
Traceback (most recent call last):
  File "/usr/local/bin/cull_idle_servers.py", line 114, in <module>
    loop.run_sync(cull)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/bin/cull_idle_servers.py", line 58, in cull_idle
    resp = yield client.fetch(req)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/simple_httpclient.py", line 307, in _on_timeout
    raise HTTPError(599, error_message)
tornado.httpclient.HTTPError: HTTP 599: Timeout while connecting
[E 2017-11-17 10:08:26.526 JupyterHub service:296] Service cull-idle exited with status 1
[I 2017-11-17 10:08:26.527 JupyterHub service:266] Starting service 'cull-idle': ['/usr/local/bin/cull_idle_servers.py', '--timeout=3600', '--cull-every=600']
[I 2017-11-17 10:08:26.528 JupyterHub service:109] Spawning /usr/local/bin/cull_idle_servers.py --timeout=3600 --cull-every=600
[D 2017-11-17 10:08:26.532 JupyterHub spawner:727] Polling subprocess every 30s
Traceback (most recent call last):
  File "/usr/local/bin/cull_idle_servers.py", line 114, in <module>
    loop.run_sync(cull)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/bin/cull_idle_servers.py", line 58, in cull_idle
    resp = yield client.fetch(req)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/simple_httpclient.py", line 307, in _on_timeout
    raise HTTPError(599, error_message)
tornado.httpclient.HTTPError: HTTP 599: Timeout while connecting
[E 2017-11-17 10:08:56.533 JupyterHub service:296] Service cull-idle exited with status 1
```
This error is still present after starting a single-user server through jupyterhub.

zero-to-jupyterhub-k8s version: `v0.4-545-g5c576aa` (Thu Nov 16 13:11:15)
Platform: openstack created with Kubespray
Deployed with: `helm install --name=jupyterhub --namespace ebi-training ./jupyterhub/ -f config-example.yml`

`config-example.yml`:
```
hub:
  baseUrl: /ebi-training/
  cookieSecret: ****************************************************************
  db:
    type: sqlite-memory
  rbac:
    enabled: true
  extraConfig: |
    # https://github.com/jupyterhub/jupyterhub/wiki/Debug-Jupyterhub
    c.JupyterHub.log_level = 'DEBUG'
    c.Spawner.debug = True

proxy:
  secretToken: ****************************************************************
  service:
    type: NodePort
  rbac:
    enabled: true

singleuser:
  memory:
    limit: 1G
    guarantee: 100M
  storage:
    type: NONE

# Disable pre-puller, fails with rbac
# https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/118
prePuller:
  enabled: false

ingress:
  enabled: true
  hosts:
  - localhost
  - kubetest-k8s-master-1
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: 16m
    ingress.kubernetes.io/proxy-read-timeout: 3600
    ingress.kubernetes.io/proxy-send-timeout: 3600
```
Could you give me some clues on where to start looking for the problem?

Thanks!

**Comment by manics** [comment]
It looks like this is a bug in our Kubernetes setup which means pods can't connect to themselves via a service IP assigned to them. I was able to work around it by overriding the IP to `127.0.0.1`: `["/usr/local/bin/cull_idle_servers.py", "--timeout=3600", "--cull-every=600", "--url=http://127.0.0.1:8081/test1/hub/api"]` though I ran into this bug: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/283

**Comment by choldgraf** [comment]
huh - that is bizarre! TYVM for the bug catch and for the follow up w/ your solution!
