### ISSUE TITLE
No module named kubernetes in 2.0.0 k8s-hub image 

### ISSUE THREAD

**Issue by rens-at-satelligence** [jupyterhub/zero-to-jupyterhub-k8s#2889]
### Bug description

I have updated our K8S jupyterhub setup using the 2.0.0 Helm chart. Updating went smooth (no errors), but now the hub has issues starting because of missing dependency `kubernetes`. 

#### Expected behaviour

Jupyterhub Hub pod to start normally.

#### Actual behaviour

Jupyterhub Hub pod fails with error :  `ModuleNotFoundError: No module named 'kubernetes'`

### Your personal set up

Installed on Kubernetes cluster using Helm and zero-to-jupyterhub instructions. Running ok for ~2 years now. Updating Helm chart to 2.0.0 caused the issue. 

The issue is related to a part in the config, where we specify k8s secrets. This worked fine with previous versions.

**Describe on Hub pod**
```
Containers:
  hub:
    Container ID:  containerd://1ddfbfb0f1a251f0ca3048e7109a24bf1b7934fd39c547f4be22312bc5686de8
    Image:         jupyterhub/k8s-hub:2.0.0
    Image ID:      docker.io/jupyterhub/k8s-hub@sha256:cd0e191901292364fbf219a4b2fd64f5b98ba02e9d9145a920105fea6e49bf71
    Port:          8081/TCP
    Host Port:     0/TCP
    Args:
      jupyterhub
      --config
      /usr/local/etc/jupyterhub/jupyterhub_config.py
      --upgrade-db
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 22 Sep 2022 08:41:53 +0200
      Finished:     Thu, 22 Sep 2022 08:41:54 +0200
    Ready:          False
    Restart Count:  6
    Requests:
      cpu:      100m
    Liveness:   http-get http://:http/hub/health delay=300s timeout=3s period=10s #success=1 #failure=30
    Readiness:  http-get http://:http/hub/health delay=0s timeout=1s period=2s #success=1 #failure=1000
    Environment:
      PYTHONUNBUFFERED:        1
      HELM_RELEASE_NAME:       dshub
      POD_NAMESPACE:           default (v1:metadata.namespace)
      CONFIGPROXY_AUTH_TOKEN:  <set to the key 'hub.config.ConfigurableHTTPProxy.auth_token' in secret 'hub'>  Optional: false
    Mounts:
      /srv/jupyterhub from pvc (rw)
      /usr/local/etc/jupyterhub/config/ from config (rw)
      /usr/local/etc/jupyterhub/jupyterhub_config.py from config (rw,path="jupyterhub_config.py")
      /usr/local/etc/jupyterhub/secret/ from secret (rw)
      /usr/local/etc/jupyterhub/z2jh.py from config (rw,path="z2jh.py")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w2zwl (ro)

```

**relevant config part**
```
  extraConfig:
    ipaddress: |
      from kubernetes import client
      def modify_pod_hook(spawner, pod):
          pod.spec.containers[0].env.append(
              client.V1EnvVar(
                  name='GS_SECRET_ACCESS_KEY',
                  value_from=client.V1EnvVarSource(
                      secret_key_ref=client.V1SecretKeySelector(
                          name='gdal-google-secret',
                          key='GS_SECRET_ACCESS_KEY',
                      )
                  )
              )
          )
          pod.spec.containers[0].env.append(
              client.V1EnvVar(
                  name='GS_ACCESS_KEY_ID',
                  value_from=client.V1EnvVarSource(
                      secret_key_ref=client.V1SecretKeySelector(
                          name='gdal-google-secret',
                          key='GS_ACCESS_KEY_ID',
                      )
                  )
              )
          )
          return pod
      c.KubeSpawner.modify_pod_hook = modify_pod_hook
```

**Full error log in Hub Pod**
```
Loading /usr/local/etc/jupyterhub/secret/values.yaml
No config at /usr/local/etc/jupyterhub/existing-secret/values.yaml
Loading extra config: ipaddress
[E 2022-09-22 06:36:37.800 JupyterHub app:3297]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/jupyterhub/app.py", line 3294, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.9/site-packages/jupyterhub/app.py", line 2773, in initialize
        self.load_config_file(self.config_file)
      File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 110, in inner
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 885, in load_config_file
        for (config, filename) in self._load_config_files(
      File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 844, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.9/site-packages/traitlets/config/loader.py", line 625, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.9/site-packages/traitlets/config/loader.py", line 658, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)
      File "/usr/local/etc/jupyterhub/jupyterhub_config.py", line 490, in <module>
        exec(config_py)
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'kubernetes'

```

**Comment by consideRatio** [comment]
Within a [large set of notes related to the upgrade](https://zero-to-jupyterhub.readthedocs.io/en/stable/administrator/upgrading/upgrade-1-to-2.html#jupyterhub-2-and-related-hub-components) this paragraph is around.

> KubeSpawner has replaced the [kubernetes](https://github.com/kubernetes-client/python) library with [kubernetes_asyncio](https://github.com/tomplus/kubernetes_asyncio). If you have extended the JupyterHub image and you rely on the kubernetes library you will need to modify your extensions.

The switch could be as simple as ensuring your functions are `async`, add `await` to calls to the k8s api, and switching the `import kubernetes` to `import kubernetes_async`.

**Comment by rens-at-satelligence** [comment]
Thank you so much for the quick reply, and apologies for not having read the changelog thoroughly enough!

**Comment by consideRatio** [comment]
No worries, thanks for a thorough issue description @rens-at-satelligence!
