### ISSUE TITLE
what's the purpose of prePuller

### ISSUE THREAD

**Issue by Peihu2020** [jupyterhub/zero-to-jupyterhub-k8s#2908]
Dear experts,

I am trying to deploy jupyterhub to my cluster by using your provided helm chart 2.0, but I got couple of errors below.

- rbac: I am an app level devops guy, so I don't have permission to do role binding
- prepuller:  k8s-image-awaiter run command failure due to no permission to call api server to get daemon set.

In order to avoid above errors, I disable rbac creation and prepuller.  After disable them, I can successfully installed hub, proxy and user-scheduler.

Because my cluster was integrated with istio, so I don't need proxy. when I try to open  hub and login by my created account, for instance admin, it returns reset errors.

**[I 2022-10-18 08:26:05.949 JupyterHub log:186] 302 GET /hub/ -> /hub/spawn (admin@10.10.128.105) 22.25ms
[E 2022-10-18 08:26:05.991 JupyterHub reflector:385] Initial list of pods failed
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/kubespawner/reflector.py", line 383, in start
        await self._list_and_update()
      File "/usr/local/lib/python3.9/site-packages/kubespawner/reflector.py", line 233, in _list_and_update
        for p in initial_resources["items"]
    KeyError: 'items'

[E 2022-10-18 08:26:05.992 JupyterHub spawner:2402] Reflector for pods failed to start.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/kubespawner/spawner.py", line 2400, in catch_reflector_start
        await f
      File "/usr/local/lib/python3.9/site-packages/kubespawner/reflector.py", line 383, in start
        await self._list_and_update()
      File "/usr/local/lib/python3.9/site-packages/kubespawner/reflector.py", line 233, in _list_and_update
        for p in initial_resources["items"]
    KeyError: 'items'

Task exception was never retrieved
future: <Task finished name='Task-174' coro=<KubeSpawner._start_reflector.<locals>.catch_reflector_start() done, defined at /usr/local/lib/python3.9/site-packages/kubespawner/spawner.py:2398> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kubespawner/spawner.py", line 2400, in catch_reflector_start
    await f
  File "/usr/local/lib/python3.9/site-packages/kubespawner/reflector.py", line 383, in start
    await self._list_and_update()
  File "/usr/local/lib/python3.9/site-packages/kubespawner/reflector.py", line 233, in _list_and_update
    for p in initial_resources["items"]
KeyError: 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyterhub/app.py", line 3313, in launch_instance
    loop.start()
  File "/usr/local/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/kubespawner/spawner.py", line 2403, in catch_reflector_start
    sys.exit(1)
SystemExit: 1
Task was destroyed but it is pending!
task: <Task pending name='Task-172' coro=<shared_client.<locals>.close_client_task() running at /usr/local/lib/python3.9/site-packages/kubespawner/clients.py:58> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fc4e62e51f0>()]>>
Exception ignored in: <coroutine object shared_client.<locals>.close_client_task at 0x7fc4e63435c0>**

My question is that can we disable both rbac and prepuller? If not, what's purpose of them. You know, only I understand their logics, and then I can apply for super user permission to deploy daemon set and call api server.

Look forward your reply.

**Comment by Peihu2020** [comment]
thanks for your answer, and let me test it based on your answer.
