### ISSUE TITLE
culling doesn't work for me yet

### ISSUE THREAD

**Issue by AaronWatters** [jupyterhub/zero-to-jupyterhub-k8s#44]
The culling mechanism is not culling servers for me.
I see this for "get pod":

cull-deployment-1750684654-bqlf1    0/1       CrashLoopBackOff   1104       3d

And in logs

`
kubectl --namespace=test logs cull-deployment-1750684654-bqlf1
Traceback (most recent call last):
  File "/srv/cull/cull_idle_servers.py", line 93, in <module>
    loop.run_sync(cull)
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/srv/cull/cull_idle_servers.py", line 42, in cull_idle
    resp = yield client.fetch(req)
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.httpclient.HTTPError: HTTP 403: Forbidden
`

**Comment by yuvipanda** [comment]
I've fixed this in v0.2 of the chart, which I've just released. I'll upgrade the guide for it tomorrow!

**Comment by yuvipanda** [comment]
Should be fixed by #47.
