### ISSUE TITLE
psycopg2 2.7.1 broken in current v0.6.0 hub image

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/zero-to-jupyterhub-k8s#451]
```
[E 2018-01-26 00:19:57.348 JupyterHub app:1623]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1620, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib/python3.6/types.py", line 204, in __next__
        return next(self.__wrapped)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1373, in initialize
        self.init_db()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 895, in init_db
        **self.db_kwargs
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/orm.py", line 526, in new_session_factory
        engine = create_engine(url, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/__init__.py", line 419, in create_engine
        return strategy.create(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/strategies.py", line 80, in create
        dbapi = dialect_cls.dbapi(**dbapi_args)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 584, in dbapi
        import psycopg2
      File "/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py", line 50, in <module>
        from psycopg2._psycopg import (                     # noqa
    ImportError: /usr/local/lib/python3.6/dist-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

```

**Comment by ryanlovett** [comment]
psycopg2 is currently at 2.7.1 in the hub image. A similar report at https://github.com/psycopg/psycopg2-wheels/issues/2 says that 2.7.3.1.dev0 fixed the problem. Others report 2.7.3 fixes it.

2.7.3.2 is the latest.
