### ISSUE TITLE
docker.errors.APIError: 400 Client Error: Bad Request

### ISSUE THREAD

**Issue by leopsidom** [jupyterhub/zero-to-jupyterhub-k8s#511]
I followed the documentation to build a docker image with custom requirements.txt. My command to build the image is as:

`jupyter-repo2docker https://github.com/leopsidom/jupyterhub-scipy.git --image=gcr.io/jupyter-server-195420/jupyter-server:cf36c6 --no-run`

It seems the image build was successful, since it gives message as follows:
```
> Successfully built b975f6103ad1
> Successfully tagged r2dhttps-3a-2f-2fgithub-2ecom-2fleopsidom-2fjupyterhub-2dscipy-2egit1519178581:latest
```
After which however it gives me an error as the title. What could be the problem?  

The whole stack trace is as:
```
> Traceback (most recent call last):
>   File "/Users/purecarscomputer/anaconda/envs/python36/lib/python3.6/site-packages/docker/api/client.py", line 223, in _raise_for_status
>     response.raise_for_status()
>   File "/Users/purecarscomputer/anaconda/envs/python36/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.35/containers/8660f603fd2e2b07c5867720847fe6c2bb443b42b78e5efec17a5a5341c30eb9/start
> 
> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "/Users/purecarscomputer/anaconda/envs/python36/bin/jupyter-repo2docker", line 11, in <module>
>     sys.exit(main())
>   File "/Users/purecarscomputer/anaconda/envs/python36/lib/python3.6/site-packages/repo2docker/__main__.py", line 6, in main
>     f.start()
>   File "/Users/purecarscomputer/anaconda/envs/python36/lib/python3.6/site-packages/repo2docker/app.py", line 585, in start
>     self.run_image()
>   File "/Users/purecarscomputer/anaconda/envs/python36/lib/python3.6/site-packages/repo2docker/app.py", line 485, in run_image
>     environment=self.environment
>   File "/Users/purecarscomputer/anaconda/envs/python36/lib/python3.6/site-packages/docker/models/containers.py", line 751, in run
>     container.start()
>   File "/Users/purecarscomputer/anaconda/envs/python36/lib/python3.6/site-packages/docker/models/containers.py", line 355, in start
>     return self.client.api.start(self.id, **kwargs)
>   File "/Users/purecarscomputer/anaconda/envs/python36/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
>     return f(self, resource_id, *args, **kwargs)
>   File "/Users/purecarscomputer/anaconda/envs/python36/lib/python3.6/site-packages/docker/api/container.py", line 1040, in start
>     self._raise_for_status(res)
>   File "/Users/purecarscomputer/anaconda/envs/python36/lib/python3.6/site-packages/docker/api/client.py", line 225, in _raise_for_status
>     raise create_api_error_from_http_exception(e)
>   File "/Users/purecarscomputer/anaconda/envs/python36/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
>     raise cls(e, response=response, explanation=explanation)
> docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"--image=gcr.io/jupyter-server-195420/jupyter-server:cf36c6\": stat --image=gcr.io/jupyter-server-195420/jupyter-server:cf36c6: no such file or directory": unknown")
```

**Comment by alanderex** [comment]
Ran into the same error,
the quick (& dirty) solution is to run that step manually, in your case:

`docker tag  r2dhttps-3a-2f-2fgithub-2ecom-2fleopsidom-2fjupyterhub-2dscipy-2egit1519178581  gcr.io/jupyter-server-195420/jupyter-server`

**Comment by betatim** [comment]
This is the same problem as in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/719 I think.

**Comment by betatim** [comment]
I'll close this, feel free to reopen if it turns out not to be a duplicate.
