### ISSUE TITLE
Spawner failure leads to troublesome hub state

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#647]
## Incident report
If the kubespawner is attempting to start, but crashes in `pre_spawn_start` due to an error, jupyterhub is left in a bad state it seems. The hub/proxy seem to think that the user is up and running (`access server`) button is available, but the user can't access it (`503 : Service Unavailable`), and the admin panel fails to stop it (`API request failed (400): erik.sundell is not running`).

<details><summary>Logs from an error in <code>pre_spawn_start</code> that caused the problematic jupyterhub state for me</summary>

```
[E 2018-04-13 04:58:03.128 JupyterHub web:1621] Uncaught exception GET /hub/user/erik.sundell/ (10.156.0.3)
    HTTPServerRequest(protocol='https', host='jupyter.se', method='GET', uri='/hub/user/erik.sundell/', version='HTTP/1.1', remote_ip='10.156.0.3')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 747, in get
        yield self.spawn_single_user(current_user)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 475, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 368, in spawn
        yield gen.maybe_future(authenticator.pre_spawn_start(self, spawner))
      File "/etc/jupyterhub/config/hub.extra-config.default.py", line 57, in pre_spawn_start
        spawner.environment['NBGITPULLER_APP'] = lab
    NameError: name 'lab' is not defined
    
[E 2018-04-13 04:58:03.135 JupyterHub log:114] {
      "Cookie": "jupyter-hub-token=\"2|1:0|10:1523039137|17:jupyter-hub-token|44:M2U1NjkxZmNmN2NkNGExOTlhMWU4MDM3ZThlNDk3ZjM=|e3b42b20c88f2d0417a9090b3edf13c53c508d83902eadd1f16bcb657cb791a5\"; _xsrf=2|81e67a9e|9b7be9047c138d3a5dc6ad96b40b5d53|1521573966",
      "Accept-Language": "en-US,en;q=0.9,sv;q=0.8",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://jupyter.se/hub/user/erik.sundell/",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "X-Scheme": "https",
      "X-Original-Uri": "/hub/user/erik.sundell/",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "jupyter.se",
      "X-Forwarded-For": "10.156.0.3,10.16.2.38",
      "X-Real-Ip": "10.156.0.3",
      "Connection": "close",
      "Host": "jupyter.se"
    }
```
</details>

## Details
I'm using z2jh master and JupyterHub 0.8.1.

## Comments
I think this issue might belong in JupyterHub or Kubespawner rather than z2jh, but I'm not sure... I'm also not confident it is important we do something about this. I believe it might become a relevant background insight of how the hub, spawner and proxy interact though and how to improve on the that interactions reliability.

**Comment by consideRatio** [comment]
Perhaps fixed, not sure, closing.
