### ISSUE TITLE
Unable to delete a pod error when Hub reports the "pod is not running" after initial cull request

### ISSUE THREAD

**Issue by willingc** [jupyterhub/zero-to-jupyterhub-k8s#652]
There are several error of this type when running:

`kubectl logs hub-6cfd8bf669-tcstv`

```
[E 180417 16:48:21 cull_idle_servers:116] Error culling ipython-ipython-in-depth-tuquu9x5
    Traceback (most recent call last):
      File "/usr/local/bin/cull_idle_servers.py", line 114, in cull_idle
        yield f
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/bin/cull_idle_servers.py", line 78, in cull_one
        resp = yield client.fetch(req)
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1099, in run
        value = future.result()
    tornado.httpclient.HTTPError: HTTP 400: Bad Request
```

It appears that the timing is off so the pod is no longer running and the culler throws an error that the pod can not fully delete. 11 minutes later the culler succeeds in deleting.

```
$ kubectl logs hub-6cfd8bf669-tcstv | grep ipython-ipython-in-depth-tuquu9x5
[I 2018-04-17 16:26:04.878 JupyterHub log:122] 201 POST /hub/api/users/ipython-ipython-in-depth-tuquu9x5 (binder@10.12.43.189) 158.02ms
[I 2018-04-17 16:26:11.594 JupyterHub base:447] User ipython-ipython-in-depth-tuquu9x5 took 6.486 seconds to start
[I 2018-04-17 16:26:11.596 JupyterHub proxy:231] Adding user ipython-ipython-in-depth-tuquu9x5 to proxy /user/ipython-ipython-in-depth-tuquu9x5/ => http://10.12.44.245:8888
[I 2018-04-17 16:26:11.614 JupyterHub log:122] 201 POST /hub/api/users/ipython-ipython-in-depth-tuquu9x5/server (binder@10.12.43.189) 6509.25ms
[I 180417 16:48:05 cull_idle_servers:73] Culling server for ipython-ipython-in-depth-tuquu9x5 (inactive since 2018-04-17 16:35:28.681000)
[W 2018-04-17 16:48:11.572 JupyterHub base:517] User ipython-ipython-in-depth-tuquu9x5 server stopped, with exit code: 1
[I 2018-04-17 16:48:11.572 JupyterHub proxy:254] Removing user ipython-ipython-in-depth-tuquu9x5 from proxy (/user/ipython-ipython-in-depth-tuquu9x5/)
[W 2018-04-17 16:48:11.624 JupyterHub web:1618] 400 DELETE /hub/api/users/ipython-ipython-in-depth-tuquu9x5/server (127.0.0.1): ipython-ipython-in-depth-tuquu9x5 is not running
[W 2018-04-17 16:48:11.633 JupyterHub log:122] 400 DELETE /hub/api/users/ipython-ipython-in-depth-tuquu9x5/server (cull-idle@127.0.0.1) 168.32ms
[E 180417 16:48:21 cull_idle_servers:116] Error culling ipython-ipython-in-depth-tuquu9x5
[I 180417 16:59:06 cull_idle_servers:88] Culling user ipython-ipython-in-depth-tuquu9x5 (inactive since 2018-04-17 16:48:11.588895)
[I 2018-04-17 16:59:12.059 JupyterHub log:122] 204 DELETE /hub/api/users/ipython-ipython-in-depth-tuquu9x5 (cull-idle@127.0.0.1) 79.55ms
```
@minrk

**Comment by clkao** [comment]
This is probably caused by the internal state inconsistency. attempted fix is https://github.com/jupyterhub/kubespawner/pull/154. but as it's an internal flag so probably should be somewhere in jupyterhub.

**Comment by dalssaso** [comment]
Hi, I'm experiencing this with the latest stable version of the Helm chart! Any updates on this?
I've the cull keeps throwing the same exception

```
[E 190215 01:04:44 cull_idle_servers:286] Error processing user
    Traceback (most recent call last):
      File "/usr/local/bin/cull_idle_servers.py", line 284, in cull_idle
        result = yield f
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/bin/cull_idle_servers.py", line 220, in handle_user
        results = yield multi(server_futures)
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 883, in callback
        result_list.append(f.result())
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/bin/cull_idle_servers.py", line 182, in handle_server
        resp = yield fetch(req)
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1147, in run
        yielded = self.gen.send(value)
      File "/usr/local/bin/cull_idle_servers.py", line 105, in fetch
        return (yield client.fetch(req))
```
The user can't access his jhub instance because it says it keeps running

**Comment by consideRatio** [comment]
I'm quite confident this is at most just a transient error by now, as JupyterHub has started checking if it can access servers and update its state with what it learns.
