### ISSUE TITLE
hub image in CrashLoopBackOff:

### ISSUE THREAD

**Issue by jhendric98** [jupyterhub/zero-to-jupyterhub-k8s#731]
I've been trying to load zero-to-jupyterhub-k8s on a kubernetes cluster running under Rancher 2.0

I've resolved the ingress and the persistent volume claim problems but I cannot get past this one. 

I believe I'm close. It is complaining on database.

The hub image crashes. I've included the logs below. Here is the config.yaml I'm using:
<config.yaml>
hub:
  cookieSecret: "aaaaaa"
proxy:
  secretToken: "bbbbbb"
ingress:
    enabled: true
    hosts:
     - url.local

<logs>
kubectl --namespace=dsjupyterhub logs hub-aaa
[I 2018-06-18 20:56:17.248 JupyterHub app:830] Loading cookie_secret from env[JPY_COOKIE_SECRET]
[E 2018-06-18 20:56:17.276 JupyterHub app:1623]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1620, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib/python3.6/types.py", line 204, in __next__
        return next(self.__wrapped)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1373, in initialize
        self.init_db()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 888, in init_db
        dbutil.upgrade_if_needed(self.db_url, log=self.log)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/dbutil.py", line 118, in upgrade_if_needed
        orm.check_db_revision(engine)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/orm.py", line 462, in check_db_revision
        current_table_names = set(engine.table_names())
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2136, in table_names
        with self._optional_conn_ctx_manager(connection) as conn:
      File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1932, in _optional_conn_ctx_manager
        with self.contextual_connect() as conn:
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
        self._wrap_pool_connect(self.pool.connect, None),
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
        e, dialect, self)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
        exc_info
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
        return fn()
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 403, in connect
        return _ConnectionFairy._checkout(self)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 782, in _checkout
        fairy = _ConnectionRecord.checkout(pool)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 532, in checkout
        rec = pool._do_get()
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 1277, in _do_get
        return self._create_connection()
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
        return _ConnectionRecord(self)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 477, in __init__
        self.__connect(first_connect_check=True)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool.py", line 667, in __connect
        connection = pool._invoke_creator(self)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/strategies.py", line 105, in connect
        return dialect.connect(*cargs, **cparams)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 410, in connect
        return self.dbapi.connect(*cargs, **cparams)
    sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)

Thanks for any help!

**Comment by manics** [comment]
What's the backing the persistent volume? E.g. sqlite has problems with NFS. Or could it be a permissions problem?

**Comment by openthings** [comment]
I am also find this problem. but using ubuntu 16.04 is success with nfs, after upgrade ubuntu 18.04, it failed, can't restart.

**Comment by openthings** [comment]
I am set NFS provisioner images to **quay.io/kubernetes_incubator/nfs-provisioner:v2.1.0-k8s1.11**, then delete the pod of NFS and jupyter's hub, when pod restarted, the problem disappeared. @manics @jhendric98

**Comment by kalaytan** [comment]
have the same error as original issue.
kubeadm with nfs storage class.
Using helm stable/nfs-client-provisioner to create storage class.

sc works as supposed to.
- I can start hub with hub.db.type: squlite-memory and use same sc for user claims.

when I change to sqlite-pvc, 
I can see the claim created, folder I specified in hub.pvc.subPath and  but same error.
On nfs user is respected. 
I tried: 
- giving 777 to hub-db-dir 
- changing hub.uid & hub.fsGid to 0 (root).

Nothing helped so far.
Possibly SQLite doesn't want to play with NFS according to https://stackoverflow.com/questions/9907429/locking-sqlite-file-on-nfs-filesystem-possible
